// data.js - Ngân hàng câu hỏi chuẩn đầy đủ 408 câu

const SUBJECTS = [
    {
        id: "cntt_nangcao",
        name: "CNTT Nâng Cao",
        icon: "💻",
        desc: "Chứng chỉ Ứng dụng CNTT Nâng cao (Word, PowerPoint, Excel, Project)",
        active: true
    },
    {
        id: "toan_hoc",
        name: "Giải Tích & Hình Học",
        icon: "📐",
        desc: "Ôn tập kiến thức Toán Đại số & Hình học",
        active: false 
    },
    {
        id: "tieng_anh",
        name: "Tiếng Anh",
        icon: "🇬🇧",
        desc: "Ngữ pháp và từ vựng Tiếng Anh",
        active: false 
    }
];

const QUESTION_BANK = {
    "cntt_nangcao": [
        // ================= PHẦN WORD (1 - 105) =================
        { s: "Word", q: "Câu 1: Muốn quay lại lệnh vừa thực hiện trong Word 2010, ta dùng:", o: { A: "Ctrl+C", B: "Ctrl+P", C: "Ctrl+Z", D: "Ctrl+Y" }, c: "C" },
        { s: "Word", q: "Câu 2: Muốn đổi kiểu chữ thường sang chữ HOA trong Word 2010, ta dùng:", o: { A: "Font/Effect/Shadow", B: "Font/Effect/All Caps", C: "Font/Effect/Small Caps", D: "Font/Effect/Strikethrough" }, c: "B" },
        { s: "Word", q: "Câu 3: Trong Word 2010, phím nào cho phép ngay lập tức đưa con trỏ về đầu dòng hiện hành:", o: { A: "Enter", B: "Insert", C: "End", D: "Home" }, c: "D" },
        { s: "Word", q: "Câu 4: Muốn cắt đối tượng đang chọn đưa vào Clipboard trong Word 2010, ta dùng:", o: { A: "Delete", B: "Cut", C: "Copy", D: "Paste" }, c: "B" },
        { s: "Word", q: "Câu 5: Muốn định dạng canh lề trái trong Word 2010, ta chọn:", o: { A: "Home/Paragraph/Align Right", B: "Home/Paragraph/Justify", C: "Home/Paragraph/Center", D: "Home/Paragraph/Align Left" }, c: "D" },
        { s: "Word", q: "Câu 6: Trong soạn thảo văn bản Word 2010, công dụng của tổ hợp phím Ctrl + O là:", o: { A: "Đóng File đang mở", B: "Mở một File đã có", C: "Mở một File mới", D: "Lưu File vào đĩa" }, c: "B" },
        { s: "Word", q: "Câu 7: Muốn dán đối tượng đã chọn đưa vào Clipboard trong Word 2010, ta dùng:", o: { A: "Delete", B: "Paste", C: "Copy", D: "Cut" }, c: "B" },
        { s: "Word", q: "Câu 8: Muốn thiết lập Tab tại vị trí tùy ý trong văn bản, ta chọn:", o: { A: "Home/Paragraph/Set as Default", B: "Home/Paragraph/Tabs", C: "Nhấn phím Tab trên bàn phím", D: "Home/Paragraph/ok" }, c: "B" },
        { s: "Word", q: "Câu 9: Muốn thiết lập khổ giấy ngang/dọc trong Word 2010, ta chọn:", o: { A: "Page Layout/Page Setup/Orientation", B: "Page Layout/Page Setup/Pages", C: "Page Layout/Page Setup/Margins", D: "Page Layout/Page Setup/Save as Default" }, c: "A" },
        { s: "Word", q: "Câu 10: Muốn chèn hình có sẵn trong thư viện trực tuyến vào văn bản trong Word 2010, ta chọn:", o: { A: "Insert/Picture", B: "Insert/Online Picture", C: "Insert/Shapes", D: "Insert/Chart" }, c: "B" },
        { s: "Word", q: "Câu 11: Muốn tạo kiểu chữ trong Word 2010, ta dùng:", o: { A: "Font/Effect/Shadow", B: "Font/Effect/Strikethrough", C: "Font/Effect/All Caps", D: "Font/Effect/Small Caps" }, c: "A" },
        { s: "Word", q: "Câu 12: Trong Microsoft Word 2010 thao tác Shift + Enter có chức năng gì:", o: { A: "Nhập dữ liệu theo hàng dọc", B: "Ngắt dòng", C: "Ngắt trang", D: "Nhập dữ liệu theo hàng ngang" }, c: "B" },
        { s: "Word", q: "Câu 13: Muốn chia nhỏ ô trong bảng trong Word 2010, ta chọn:", o: { A: "Tables Tools/Layout/Tables", B: "Tables Tools/Layout/Cell Size", C: "Tables Tools/Layout/Merge Cells", D: "Tables Tools/Layout/Split Cells" }, c: "D" },
        { s: "Word", q: "Câu 14: Đề mục của bảng khi chuyển trang vẫn giữ nguyên trong Word 2010, ta chọn:", o: { A: "Tables Properties/Cell", B: "Tables Properties/Row", C: "Tables Properties/Column", D: "Tables Properties/Table" }, c: "B" },
        { s: "Word", q: "Câu 15: Trong Word 2010 để thực hiện tạo trộn thư Mail Merge, ta thực hiện:", o: { A: "Thẻ Mailings/Start Mail Merge/Step by step Mail Merge wizard", B: "Mailings/Start Mail Merge/ Start Mail Merge", C: "The Mailings Write&Insert Fields/Insert Merge Field", D: "Thẻ Mailings/Create/Enverlopes" }, c: "A" },
        { s: "Word", q: "Câu 16: Muốn thiết lập kiểu chữ in đậm trong Word 2010, ta chọn:", o: { A: "Ctrl+U", B: "Ctrl+Y", C: "Ctrl+B", D: "Ctrl+I" }, c: "C" },
        { s: "Word", q: "Câu 17: Hiện nay, trong Word 2010 ở Việt Nam thường sử dụng bảng mã nào để gõ Tiếng Việt:", o: { A: "TCVN3 (ABC)", B: "Unicode", C: "VIQR", D: "VNI Windows" }, c: "B" },
        { s: "Word", q: "Câu 18: Shapes trong Word 2010 có tác dụng:", o: { A: "Chèn biểu đồ", B: "Chèn hình ảnh", C: "Chèn phim", D: "Vẽ hình" }, c: "D" },
        { s: "Word", q: "Câu 19: Trong soạn thảo Word 2010, muốn trình bày văn bản dạng cột, ta thực hiện:", o: { A: "View/Print Layout", B: "Table/Column", C: "Insert/Table", D: "Page Layout/Columns" }, c: "D" },
        { s: "Word", q: "Câu 20: Muốn di chuyển một đoạn văn bản trong Word 2010, ta dùng:", o: { A: "Alt+C và Ctrl+V", B: "Alt+X và Ctrl+V", C: "Ctrl+X và Ctrl+V", D: "Ctrl+C và Ctrl+V" }, c: "C" },
        { s: "Word", q: "Câu 21: Muốn in tài liệu trong word 2010, ta dùng:", o: { A: "File/Close", B: "File/Print", C: "File/Share", D: "File/Options" }, c: "B" },
        { s: "Word", q: "Câu 22: Tổ hợp phím Ctrl+Z trong Word 2010 dùng để:", o: { A: "Hủy kết quả của thao tác hoặc lệnh phía trước gần nhất kết quả hiện tại", B: "Hủy thao tác", C: "Đóng tập tin đang mở", D: "Đóng cửa sổ đang mở" }, c: "A" },
        { s: "Word", q: "Câu 23: Để chèn một siêu liên kết vào văn bản đang soạn thảo tại vị trí con trỏ trong Word 2010, ta sử dụng:", o: { A: "Insert/Chart", B: "Insert/Links", C: "Insert/Shapes", D: "Insert/Smart Art" }, c: "B" },
        { s: "Word", q: "Câu 24: Trong Word 2010, Insert -> Page Number -> Current Position, tính năng này dùng để chèn số trang vào:", o: { A: "Giữa cuối trang tài liệu", B: "Bên trái cuối trang tài liệu", C: "Bên phải cuối trang tài liệu", D: "Vị trí con trỏ của tài liệu" }, c: "D" },
        { s: "Word", q: "Câu 25: Để chỉnh sửa hình ảnh chèn vào văn bản hiển thị giống như các chữ trong văn bản trong Word 2010, ta dùng:", o: { A: "Picture Tool/Format/Text Wrapping/In Front of Text", B: "Picture Tool/Format/Text Wrapping/Tight", C: "Picture Tool/Format/Text Wrapping/In Lines With Text", D: "Picture Tool/Format/Text Wrapping/Behind Text" }, c: "C" },
        { s: "Word", q: "Câu 26: Chức năng Repeat as header row at the top of each page trong Word 2010, có tác dụng:", o: { A: "Tạo tiêu đề cho đoạn văn bản trong bảng", B: "Tạo tiêu đề lặp lại cho trang văn bản", C: "Tạo tiêu đề lặp lại bảng biểu khi chuyển trang", D: "Tạo tiêu đề cho văn bản" }, c: "C" },
        { s: "Word", q: "Câu 27: Phát biểu nào sai khi nói về chức năng Mail Merge trong Word 2010?", o: { A: "Tập tin dữ liệu có thể được tạo bằng Word 2010 hoặc Excel 2010", B: "Phải có hai tập tin: tập tin dữ liệu và tập tin chính", C: "Mail Merge có thể gửi và nhận thư điện tử giống Gmail", D: "Mail Merge thường được sử dụng để tạo thư mời hay phiếu báo điểm" }, c: "C" },
        { s: "Word", q: "Câu 28: Trong Word 2010, để chuyển nhanh đến một điểm đánh dấu văn bản (Bookmark), với hộp thoại trong hình vẽ để thực hiện:", o: { A: "Go To", B: "Delete", C: "Cancel", D: "Add" }, c: "A" },
        { s: "Word", q: "Câu 29: Muốn chèn số tự động cho đoạn văn bản trong Word 2010, ta chọn:", o: { A: "Home/Paragraph/Bullets", B: "Home/Paragraph/Numbering", C: "Home/Paragraph/Center", D: "Home/Paragraph/Multilevel" }, c: "B" },
        { s: "Word", q: "Câu 30: Trong khi làm việc với Word 2010, tổ hợp phím tắt nào cho phép chọn tất cả văn bản đang soạn thảo:", o: { A: "Ctrl+A", B: "Ctrl+F", C: "Alt+A", D: "Alt+F" }, c: "A" },
        { s: "Word", q: "Câu 31: Để gạch dưới mỗi từ một nét đôi trong Word 2010, sử dụng tổ hợp phím nào?", o: { A: "Ctrl+Shift+K", B: "Ctrl+Shift+D", C: "Ctrl+Shift+W", D: "Ctrl+Shift+A" }, c: "B" },
        { s: "Word", q: "Câu 32: Trong Word 2010, khi di chuyển con trỏ trong bảng phím Tab dùng để:", o: { A: "Di chuyển con trỏ qua các ô theo hướng từ phải qua trái", B: "Di chuyển con trỏ qua các ô theo hướng từ trái qua phải, từ trên xuống dưới", C: "Thêm 1 Tab vào ô", D: "Không có chức năng gì" }, c: "B" },
        { s: "Word", q: "Câu 33: Trong soạn thảo văn bản Word 2010, công dụng của tổ hợp phím Ctrl + H là:", o: { A: "Lưu tập tin văn bản vào đĩa", B: "Định dạng chữ hoa", C: "Chức năng tìm và thay thế trong soạn thảo", D: "Tạo tập tin văn bản mới" }, c: "C" },
        { s: "Word", q: "Câu 34: Để thu hẹp khoảng cách giữa các ký tự trong Word 2010, ta thực hiện:", o: { A: "Home/Font/Advanced/Character Spacing/Condensed", B: "Home/Font/Advanced/Character Spacing/Expanded", C: "A và B đúng", D: "A và B sai" }, c: "A" },
        { s: "Word", q: "Câu 35: Chức năng Margins trong Word 2010 có tác dụng:", o: { A: "Chọn độ rộng của lề giấy (trái, phải, trên, dưới)", B: "Chọn chiều in (ngang hoặc dọc)", C: "Chọn kiểu giấy in (A5, A4...)", D: "Chọn số cột văn bản" }, c: "A" },
        { s: "Word", q: "Câu 36: Chức năng Text Box trong Word 2010 có tác dụng gì:", o: { A: "Tạo chữ nghệ thuật", B: "Tạo chữ lớn đầu dòng đoạn văn bản", C: "Tạo tiêu đề văn bản", D: "Tạo hộp văn bản" }, c: "D" },
        { s: "Word", q: "Câu 37: Trong Word 2010 khi văn bản đã bật chức năng Track Changes, chọn Review -> Accept -> Accept All Changes in Document để:", o: { A: "Loại bỏ hết tất cả các thay đổi", B: "Bật chức năng theo dõi lịch sử", C: "Đồng ý lưu lại tất cả các thay đổi của văn bản đã được chỉnh sửa", D: "Thiết lập mật khẩu" }, c: "C" },
        { s: "Word", q: "Câu 38: Trong Word 2010, dòng chữ “Cộng hòa xã hội chủ nghĩa Việt Nam” nhập bằng font Times New Roman, bảng mã Unicode, khẳng định nào đúng?", o: { A: "Để hiển thị đúng bằng font .VnTimes, bạn cần sử dụng một phần mềm như Unikey để chuyển đổi mã", B: "Có thể chuyển sang font .VnTimes bằng cách bôi đen...", C: "Có thể nhấn chuột vào nút Home...", D: "Để chuyển font mà vẫn đọc bình thường..." }, c: "A" },
        { s: "Word", q: "Câu 39: Muốn định dạng căn lề giữa trong Word 2010, ta chọn:", o: { A: "Home/Paragraph/Align Right", B: "Home/Paragraph/Center", C: "Home/Paragraph/Justify", D: "Home/Paragraph/Align Left" }, c: "B" },
        { s: "Word", q: "Câu 40: Trong Word 2010, khi con trỏ ở ô cuối cùng trong bảng, nếu nhấn phím Tab thì:", o: { A: "Con trỏ sẽ nhảy xuống đoạn văn bản bên dưới bảng", B: "Con trỏ đứng yên khi hết bảng", C: "Sẽ tạo thêm một dòng mới trong bảng", D: "Con trỏ nhảy về ô đầu tiên của bảng" }, c: "C" },
        { s: "Word", q: "Câu 41: Muốn tạo mới một tài liệu trong Word 2010, ta dùng:", o: { A: "File/Close", B: "File/New", C: "File/Open", D: "File/Save" }, c: "B" },
        { s: "Word", q: "Câu 42: Trong Word 2010, lưu văn bản thành tập tin PDF, ta chọn:", o: { A: "File/Save As/PDF or XPS", B: "File/Options/Save as/Word 2010 Template", C: "File/Options/Save as/ Word 2010 97-2003 Document", D: "File/Options/Save as/ Word 2010 Document" }, c: "A" },
        { s: "Word", q: "Câu 43: Để chọn cỡ chữ trong Word 2010, ta thực hiện:", o: { A: "Shift+P", B: "Alt+Shift+P", C: "Ctrl+Shift+P", D: "Ctrl+Alt+P" }, c: "C" },
        { s: "Word", q: "Câu 44: Trong Word 2010, để tạo một siêu liên kết chỉ tới 1 chương trong văn bản đang soạn, thực hiện lựa chọn:", o: { A: "E-mail Address", B: "Create New Document", C: "Existing File or Web Page", D: "Place in This Document" }, c: "D" },
        { s: "Word", q: "Câu 45: Trong Word 2010, khi con trỏ đang ở trang soạn thảo thứ 8, muốn xem nội dung trang 31, ta thực hiện:", o: { A: "Nhấn Alt + G/Nhập 31/Enter", B: "Nhấn Shift + G/Nhập 31/Enter", C: "Nhấn Ctrl + G/Nhập 31/Enter", D: "Nhấn Ctrl + Shift + G/Nhập 31/Enter" }, c: "C" },
        { s: "Word", q: "Câu 46: Trong Word 2010, tổ hợp phím nào cho phép ngay lập tức đưa con trỏ về dòng đầu tiên của văn bản:", o: { A: "Alt + Home", B: "Shift + Home", C: "Ctrl + Home", D: "Ctrl+Alt + Home" }, c: "C" },
        { s: "Word", q: "Câu 47: Chọn phát biểu sai, trong Word 2010:", o: { A: "Chức năng Text Wrapping xuất hiện khi chèn 1 ảnh vào văn bản", B: "Chức năng Text Wrapping xuất hiện khi chèn 1 bảng vào văn bản", C: "Chức năng Text Wrapping xuất hiện khi chèn 1 chữ nghệ thuật vào văn bản", D: "Chức năng Text Wrapping xuất hiện khi chèn 1 hình vẽ vào văn bản" }, c: "B" },
        { s: "Word", q: "Câu 48: Muốn chèn một bảng vào văn bản trong Word 2010, ta chọn:", o: { A: "Insert/Tables", B: "Insert/Pages", C: "Insert/Header", D: "Insert/Links" }, c: "A" },
        { s: "Word", q: "Câu 49: Trong Word 2010, muốn in trang 1 đến trang 3, ta chọn mục nào:", o: { A: "File/Print/Printer", B: "File/Print/Print", C: "File/Print/Settings/Pages", D: "File/Print/Copies" }, c: "C" },
        { s: "Word", q: "Câu 50: Trong Word 2010, ở menu chính chọn Review -> Track Changes -> Track Changes để:", o: { A: "Thiết lập mật khẩu", B: "Bật chức năng theo dõi lịch sử chỉnh sửa văn bản", C: "Loại bỏ thiết lập mật khẩu", D: "Thay đổi các thông số mặc định" }, c: "B" },
        { s: "Word", q: "Câu 51: Muốn chọn căn chỉnh dữ liệu trong bảng trong Word 2010, ta chọn:", o: { A: "Table Tools/Layout/Alignment", B: "Table Tools/Layout/Merge Cells", C: "Table Tools/Layout/Tables", D: "Table Tools/Layout/Cell Size" }, c: "A" },
        { s: "Word", q: "Câu 52: Chức năng Page Layout/Size trong Word 2010 có tác dụng:", o: { A: "Chọn kiểu giấy in (A5, A4,...)", B: "Chọn độ rộng của lề giấy", C: "Chọn chiều in (ngang hoặc dọc)", D: "Chọn số cột văn bản" }, c: "A" },
        { s: "Word", q: "Câu 53: Đang gõ văn bản trong MS Word 2010 và dưới chân những ký tự bạn đang gõ xuất hiện các dấu xanh là vì:", o: { A: "Máy tính bị virus", B: "Vấn đề chính tả", C: "Dùng sai từ tiếng Anh", D: "Gõ sai quy tắc ngữ pháp" }, c: "D" },
        { s: "Word", q: "Câu 54: Trong Word 2010, muốn thiết lập kích thước chữ, kiểu chữ, ta chọn:", o: { A: "Home/Clipboard", B: "Home/Paragraph", C: "Home/Font", D: "Home/Styles" }, c: "C" },
        { s: "Word", q: "Câu 55: Muốn thiết lập số cột văn bản trong Word 2010, ta chọn:", o: { A: "Page Layout/Page Setup/Size", B: "Page Layout/Page Setup/Margins", C: "Page Layout/Page Setup/Orientation", D: "Page Layout/Page Setup/Columns" }, c: "D" },
        { s: "Word", q: "Câu 56: Muốn mở tài liệu đã có trên ổ đĩa trong Word 2010, ta dùng:", o: { A: "File/Save", B: "File/Close", C: "File/Open", D: "File/New" }, c: "C" },
        { s: "Word", q: "Câu 57: Muốn thoát khỏi chương trình trong Word 2010, ta dùng:", o: { A: "File/Share", B: "File/Close", C: "File/Options", D: "File/Print" }, c: "B" },
        { s: "Word", q: "Câu 58: Trong Word 2010, khi quét khối văn bản xong vào: Page Layout/Page Setup/Layout/Borders/Borders cho phép ta làm gì:", o: { A: "Tô nền cho đoạn văn bản", B: "Đóng khung cho đoạn văn bản", C: "Đóng khung cho trang giấy", D: "Tạo tiêu đề" }, c: "B" },
        { s: "Word", q: "Câu 59: Muốn sắp xếp theo thứ tự ABC trong Word 2010, ta dùng:", o: { A: "Home/Paragraph/Shading", B: "Home/Paragraph/Sort", C: "Home/Paragraph/Numbering", D: "Home/Paragraph/Bullets" }, c: "B" },
        { s: "Word", q: "Câu 60: Cho biết phát biểu nào dưới đây là sai trong Word 2010:", o: { A: "Bấm Ctrl+X tương đương với nhấn nút Cut", B: "Bấm Ctrl+C tương đương với nhấn nút Copy", C: "Bấm Ctrl+V tương đương với nhấn nút Paste", D: "Bấm Ctrl+P tương đương với nhấn nút Format Painter" }, c: "D" },
        { s: "Word", q: "Câu 61: Trong file Word 2010, để thực hiện đặt mật khẩu cho tập tin, ta thực hiện:", o: { A: "File/Info/Protect Document", B: "File/Prepare/Info/Protect Document", C: "File/Save As/Tools/General Options", D: "A và C đúng" }, c: "D" },
        { s: "Word", q: "Câu 62: Chức năng Symbol trong Word 2010 có tác dụng gì?", o: { A: "Chèn công thức toán học", B: "Chèn kí tự đặc biệt", C: "Chèn tiêu đề văn bản", D: "Chèn chữ nghệ thuật" }, c: "B" },
        { s: "Word", q: "Câu 63: Chọn Developer -> Check Box Content Control, tính năng này dùng để:", o: { A: "Tạo ô cho phép tự động lựa chọn ngày tháng năm", B: "Xóa ô lựa chọn", C: "Tạo ô cho phép người dùng đánh dấu chọn", D: "Xóa ô đánh dấu" }, c: "C" },
        { s: "Word", q: "Câu 64: Trong Word 2010, để ngắt trang bắt buộc, ta có thể nhấn tổ hợp phím nào?", o: { A: "Ctrl + Enter", B: "Shift + Enter", C: "Enter", D: "Alt + Enter" }, c: "A" },
        { s: "Word", q: "Câu 65: Muốn hòa nhập ô trong Word 2010, ta chọn:", o: { A: "Table Tools/Layout/Merge Cells", B: "Table Tools/Layout/Tables", C: "Table Tools/Layout/Delete", D: "Table Tools/Layout/Cell Size" }, c: "A" },
        { s: "Word", q: "Câu 66: Trong Word 2010, để thực hiện tạo trộn thư Mail Merge, ta thực hiện:", o: { A: "Thẻ Mailings/Start Mail Merge/Step by Step Mail Merge wizard", B: "Thẻ Mailings/Create/Envelopes", C: "Mailings/Start Mail Merge/Start Mail Merge", D: "Thẻ Mailings/Insert Merge Field" }, c: "A" },
        { s: "Word", q: "Câu 67: Trong Word 2010, khi bấm chuột phải vào văn bản đã nhúng chọn Document Object -> Open, tính năng này dùng để:", o: { A: "Xóa bỏ tập tin", B: "Chuyển đổi tập tin", C: "Ẩn tập tin", D: "Chỉnh sửa tập tin văn bản đã nhúng" }, c: "D" },
        { s: "Word", q: "Câu 68: Chức năng Finish & Merge trong Mailings trong Word 2010 có tác dụng:", o: { A: "Thực hiện thao tác in thư đã được trộn", B: "Thực hiện thao tác chọn danh sách các trường", C: "Thực hiện thao tác hoàn tất quá trình trộn thư (In, Email, Lưu file)", D: "Thêm một trường" }, c: "C" },
        { s: "Word", q: "Câu 69: Khi chèn hình ảnh trong Word 2010, tùy chọn nào cho phép các chữ ôm sát hình ảnh:", o: { A: "Tight", B: "In Line With Text", C: "In Front Of Text", D: "Square" }, c: "A" },
        { s: "Word", q: "Câu 70: Trong bảng trong Word 2010, muốn chèn thêm một cột bên phải cột làm mốc, ta chọn:", o: { A: "Table Tools/Layout/Insert Below", B: "Table Tools/Layout/Insert Left", C: "Table Tools/Layout/Insert Above", D: "Table Tools/Layout/Insert Right" }, c: "D" },
        { s: "Word", q: "Câu 71: Đề mục của bảng khi chuyển trang vẫn giữ nguyên trong Word 2010, ta chọn:", o: { A: "Table Properties/Column", B: "Table Properties/Row -> Repeat as header row", C: "Table Properties/Table", D: "Table Properties/Cell" }, c: "B" },
        { s: "Word", q: "Câu 72: Microsoft Word 2010 là:", o: { A: "Phần mềm hệ thống", B: "Phần mềm bảng tính", C: "Phần mềm quản lý", D: "Phần mềm xử lý văn bản" }, c: "D" },
        { s: "Word", q: "Câu 73: Chức năng Word Art trong Word 2010 có tác dụng gì:", o: { A: "Tạo chữ nghệ thuật", B: "Tạo chữ lớn đầu dòng", C: "Tạo tiêu đề văn bản", D: "Tạo hộp văn bản" }, c: "A" },
        { s: "Word", q: "Câu 74: Chức năng Paste Special trong Word 2010 cho phép:", o: { A: "Dán văn bản theo kiểu định dạng định nghĩa", B: "Dán văn bản theo .TXT", C: "Dán văn bản không định dạng", D: "Dán văn bản theo kiểu định dạng có sẵn khi sao chép" }, c: "D" },
        { s: "Word", q: "Câu 75: Muốn xóa một cột hoặc một dòng trong bảng trong Word 2010, ta dùng:", o: { A: "Chọn dòng/cột muốn xóa/Nhấn chuột phải/Insert", B: "Chọn dòng/cột muốn xóa/Nhấn chuột phải/Delete Cells", C: "Chọn dòng/cột muốn xóa/Nhấn chuột phải/Delete", D: "B và C đều đúng" }, c: "B" },
        { s: "Word", q: "Câu 76: Trong Word 2010, không thể thực hiện được việc?", o: { A: "Sao chép một đoạn văn bản và dán nhiều lần liên tục", B: "Vẽ bảng biểu trong văn bản", C: "Chèn ảnh vào trang văn bản", D: "Kiểm tra lỗi chính tả Tiếng Việt hoàn toàn tự động chuyên sâu" }, c: "D" },
        { s: "Word", q: "Câu 77: Trong Word 2010, để vừa gõ chữ HOA và chữ thường ta dùng phím:", o: { A: "Tab", B: "Ctrl", C: "Shift", D: "Caps lock" }, c: "C" },
        { s: "Word", q: "Câu 78: Hãy chọn nội dung chữ còn thiếu trong đoạn văn bản về biểu mẫu trong Word 2010:", o: { A: "Biểu mẫu", B: "Video", C: "Hình ảnh", D: "Biểu đồ" }, c: "A" },
        { s: "Word", q: "Câu 79: Để tạo ảnh nền (chìm) cho văn bản trong Word 2010, ta chọn:", o: { A: "Design/Colors", B: "Design/Themes", C: "Page Layout/Watermark", D: "Design/Effects" }, c: "C" },
        { s: "Word", q: "Câu 80: Trong Word 2010 để ngắt trang ta thực hiện:", o: { A: "Insert/Pages/Cover Page", B: "Insert/Pages/Page Break", C: "Insert/Pages/Cover Page/Banded", D: "Insert/Pages/Blank Page" }, c: "B" },
        { s: "Word", q: "Câu 81: Muốn cài chức năng tự động lưu văn bản trong Microsoft Word 2010, ta dùng:", o: { A: "File/Options/Customize", B: "File/Options/Advanced", C: "File/Options/Display", D: "File/Options/Save" }, c: "D" },
        { s: "Word", q: "Câu 82: Trong Word 2010, để cập nhật thời gian hiện tại cho trường (field), ta chọn:", o: { A: "Update Field", B: "Numbering", C: "Toggle Field Codes", D: "Edit Field..." }, c: "A" },
        { s: "Word", q: "Câu 83: Trong Word 2010, tùy chỉnh phím tắt trong Customize Ribbon chọn:", o: { A: "Tổ hợp phím F1+I", B: "Tổ hợp phím Ctrl + F1", C: "Tổ hợp phím Tab + F1", D: "Tổ hợp phím Ctrl + Alt" }, c: "B" },
        { s: "Word", q: "Câu 84: Trong Word 2010, thông báo 'The file... already exists' xuất hiện khi nào?", o: { A: "Khi đóng văn bản chưa lưu", B: "Khi lưu văn bản trùng tên với file đã có", C: "Không chọn phông chữ", D: "Không đặt tên file" }, c: "B" },
        { s: "Word", q: "Câu 85: Khi chèn hình ảnh trong Word 2010, tùy chọn nào cho phép các chữ tạo thành hình vuông chứa hình ảnh:", o: { A: "In Front Of Text", B: "Square", C: "In Line With Text", D: "Tight" }, c: "B" },
        { s: "Word", q: "Câu 86: Muốn tạo đường viền cho đoạn văn bản trong Word 2010, ta chọn:", o: { A: "Home/Paragraph/Multilevel List", B: "Home/Paragraph/Borders", C: "Home/Paragraph/Bullets", D: "Home/Paragraph/Center" }, c: "B" },
        { s: "Word", q: "Câu 87: Trong Word 2010, để thiết lập đường thẳng ngăn giữa các cột văn bản, ta chọn:", o: { A: "Columns/Left", B: "Page Layout/Columns/More Columns/Line Between", C: "Columns/Right", D: "Spacing" }, c: "B" },
        { s: "Word", q: "Câu 88: Muốn đặt số trang có văn bản trong Word 2010, ta chọn:", o: { A: "Insert/Footer", B: "Insert/Header", C: "Insert/Date & Time", D: "Insert/Page Number" }, c: "D" },
        { s: "Word", q: "Câu 89: Muốn định dạng canh lề trái trong Word 2010, ta chọn:", o: { A: "Home/Paragraph/Align Right", B: "Home/Paragraph/Justify", C: "Home/Paragraph/Center", D: "Home/Paragraph/Align Left" }, c: "D" },
        { s: "Word", q: "Câu 90: Trong soạn thảo văn bản Word 2010, công dụng của tổ hợp phím Ctrl + O là:", o: { A: "Đóng File", B: "Mở một File đã có", C: "Mở File mới", D: "Lưu File" }, c: "B" },
        { s: "Word", q: "Câu 91: Muốn dán đối tượng đã chọn từ Clipboard trong Word 2010, ta dùng:", o: { A: "Delete", B: "Paste", C: "Copy", D: "Cut" }, c: "B" },
        { s: "Word", q: "Câu 92: Muốn thiết lập Tab tại vị trí tùy ý trong văn bản, ta chọn:", o: { A: "Set as Default", B: "Home/Paragraph/Tabs", C: "Nhấn Tab", D: "OK" }, c: "B" },
        { s: "Word", q: "Câu 93: Muốn thiết lập khổ giấy ngang/dọc trong Word 2010, ta chọn:", o: { A: "Page Layout/Page Setup/Orientation", B: "Pages", C: "Margins", D: "Save as Default" }, c: "A" },
        { s: "Word", q: "Câu 94: Khi chèn hình ảnh trong Word 2010, tùy chọn cho chữ tạo thành hình vuông chứa ảnh:", o: { A: "In Front Of Text", B: "Square", C: "In Line With Text", D: "Tight" }, c: "B" },
        { s: "Word", q: "Câu 95: Muốn tạo đường viền cho đoạn văn bản trong Word 2010, ta chọn:", o: { A: "Multilevel List", B: "Home/Paragraph/Borders", C: "Bullets", D: "Center" }, c: "B" },
        { s: "Word", q: "Câu 96: Trong Word 2010, để thiết lập đường thẳng ngăn giữa các cột văn bản, ta chọn:", o: { A: "Columns/Left", B: "Columns/More Columns/Line Between", C: "Columns/Right", D: "Spacing" }, c: "B" },
        { s: "Word", q: "Câu 97: Muốn đặt số trang có văn bản trong Word 2010, ta chọn:", o: { A: "Footer", B: "Header", C: "Date & Time", D: "Page Number" }, c: "D" },
        { s: "Word", q: "Câu 98: Để bức hình chèn vào văn bản hiển thị ẩn sau văn bản trong Word 2010, ta dùng:", o: { A: "In Front of Text", B: "In lines with Text", C: "Tight", D: "Behind Text" }, c: "D" },
        { s: "Word", q: "Câu 99: Trong Word 2010, font chữ nào dùng soạn thảo tiếng Việt khi chọn bảng mã Unicode:", o: { A: "VnTimes, .VnArial", B: "Times New Roman, Arial, Tahoma", C: "VnTimes, Arial", D: "Tahoma, VnAvant" }, c: "B" },
        { s: "Word", q: "Câu 100: Để chọn hiển thị thước kẻ cho Word 2010, ta dùng mục:", o: { A: "Insert", B: "View", C: "Home", D: "Page Layout" }, c: "B" },
        { s: "Word", q: "Câu 101: Trong Word 2010, để gõ chữ HOA liên tục ta dùng phím:", o: { A: "Shift", B: "Ctrl", C: "Tab", D: "Caps Lock" }, c: "D" },
        { s: "Word", q: "Câu 102: Chức năng Equation trong Word 2010 có tác dụng:", o: { A: "Chèn ký tự đặc biệt", B: "Chèn tiêu đề", C: "Chèn hình ảnh", D: "Chèn công thức toán học" }, c: "D" },
        { s: "Word", q: "Câu 103: Muốn chèn chữ nghệ thuật trong Word 2010, ta chọn:", o: { A: "Insert/TextBox", B: "Insert/WordArt", C: "Insert/Quick Parts", D: "Insert/Drop Cap" }, c: "B" },
        { s: "Word", q: "Câu 104: Trong Word 2010, để ngắt trang ta thực hiện:", o: { A: "Blank Page", B: "Cover Page", C: "Faced", D: "Page Break" }, c: "D" },
        { s: "Word", q: "Câu 105: Trong Word 2010, để tạo chú thích cho hình ảnh, ta chọn:", o: { A: "References/Captions/Update Table", B: "Cross-reference", C: "Insert Table of Figures", D: "References/Captions/Insert Caption" }, c: "D" },

        // ================= PHẦN POWERPOINT (106 - 197) =================
        { s: "PowerPoint", q: "Câu 106: Trong PowerPoint 2010, chế độ Black and unblack slide show khi trình chiếu dùng để:", o: { A: "Bôi đen một Slide", B: "Biến màn hình chuyển sang màu đen/trắng", C: "Biến màn hình trình chiếu chuyển sang toàn bộ màu đen và ngược lại", D: "Xóa bôi đen" }, c: "C" },
        { s: "PowerPoint", q: "Câu 107: Để lập trình nhúng Visual Basic for Application trong PowerPoint 2010, cần hiển thị thanh công cụ:", o: { A: "Macros", B: "Visual Basic", C: "Macro Security", D: "Developer" }, c: "D" },
        { s: "PowerPoint", q: "Câu 108: Trong PowerPoint 2010, để viết hoa tất cả các ký tự trừ ký tự đầu của mỗi từ:", o: { A: "Sentence case", B: "Uppercase", C: "Capitalize each Word", D: "Toggle case" }, c: "D" },
        { s: "PowerPoint", q: "Câu 109: Trong PowerPoint 2010, chế độ See all the slides khi trình chiếu dùng để:", o: { A: "Phóng to", B: "Xem tất cả slide trên một màn hình", C: "Nhiều cửa sổ", D: "Thu nhỏ tất cả các slide để nhìn thấy và lựa chọn dễ dàng" }, c: "D" },
        { s: "PowerPoint", q: "Câu 110: Trong PowerPoint 2010, muốn tạo một sơ đồ tổ chức, ta dùng lệnh:", o: { A: "Insert/Chart", B: "Insert/Shapes", C: "Home/Drawing", D: "Insert/Smart Art" }, c: "D" },
        { s: "PowerPoint", q: "Câu 111: Trong PowerPoint 2010, để làm xuất hiện một đối tượng trên màn hình dùng hiệu ứng nhóm:", o: { A: "Entrance", B: "Emphasis", C: "Exit", D: "Motion Paths" }, c: "A" },
        { s: "PowerPoint", q: "Câu 112: Trong PowerPoint 2010, muốn đánh số cho từng Slide, ta dùng lệnh:", o: { A: "Format/Bullets", B: "Insert/Slide Number", C: "Insert/Bullets", D: "Sai hết" }, c: "B" },
        { s: "PowerPoint", q: "Câu 113: Trong PowerPoint 2010, muốn thêm Header và Footer vào các Slide, ta thực hiện:", o: { A: "Insert/Header and Footer", B: "Sai hết", C: "View/Header and Footer", D: "View/Notes Page" }, c: "A" },
        { s: "PowerPoint", q: "Câu 114: Trong PowerPoint 2010, để chia đoạn văn thành nhiều cột ta làm thao tác:", o: { A: "Home/Line Spacing", B: "Home/Add or Remove Columns", C: "Home/Increase List Level", D: "Home/Decrease List Level" }, c: "B" },
        { s: "PowerPoint", q: "Câu 115: Trong PowerPoint 2010, để gạch ngang các ký tự được chọn:", o: { A: "Home/Font/Strikethrough", B: "Character Spacing", C: "TextShadow", D: "Underline" }, c: "A" },
        { s: "PowerPoint", q: "Câu 116: Trong PowerPoint 2010, định dạng khung văn bản theo kiểu dáng có sẵn:", o: { A: "Home/Drawing/Quick Styles", B: "Shape Fill", C: "Shape Effects", D: "Shape Outline" }, c: "A" },
        { s: "PowerPoint", q: "Câu 117: Muốn in 6 slide trên một khổ giấy A4 nằm ngang, cách nào không đúng?", o: { A: "Ctrl+P/6 Slides Horizontal/Landscape", B: "Ctrl+P/6 Slides Vertical/Landscape", C: "File/Print/6 Slides Horizontal/Portrait", D: "File/Print/6 Slides Horizontal/Landscape" }, c: "C" },
        { s: "PowerPoint", q: "Câu 118: Trong PowerPoint 2010, khi cần dùng các ký hiệu toán học (căn số, phân số...):", o: { A: "Format/Object", B: "Cả A và B đúng", C: "Insert/Object/Microsoft Equation 3.0", D: "Cả A và B sai" }, c: "C" },
        { s: "PowerPoint", q: "Câu 119: Trong PowerPoint 2010, muốn sắp xếp các slide được dễ dàng hơn, ta dùng lệnh:", o: { A: "File/New", B: "View/Slide Sorter", C: "Sai hết", D: "View/Normal" }, c: "B" },
        { s: "PowerPoint", q: "Câu 120: Lợi ích của việc sử dụng Template trong PowerPoint 2010:", o: { A: "Hạn chế lỗi", B: "Giảm thời gian trình chiếu", C: "Thiết định sẵn thời gian", D: "Giảm bớt thời gian thiết kế slide" }, c: "D" },
        { s: "PowerPoint", q: "Câu 121: Muốn sửa nhanh nội dung giống nhau giữa các slide không bị bỏ sót:", o: { A: "Find and Replace/Replace", B: "Find and Replace/Replace All", C: "Ctrl+F/Replace", D: "Duplicate Slide" }, c: "B" },
        { s: "PowerPoint", q: "Câu 122: Để đưa họ tên vào cuối slide làm tiêu đề chân trang, người thiết kế phải:", o: { A: "Insert/Header and Footer", B: "View/Header and Footer", C: "Sai hết", D: "Cả A và B đúng" }, c: "A" },
        { s: "PowerPoint", q: "Câu 123: Thay đổi màu vĩnh viễn khung văn bản, cách nào không đúng?", o: { A: "Format/Shape Style", B: "Home/Drawing/Shape Fill", C: "Shape Outline (tô màu viền)", D: "Home/Drawing/Shape Outline" }, c: "C" },
        { s: "PowerPoint", q: "Câu 124: Đang trình chiếu muốn chuyển đến slide đầu tiên:", o: { A: "Ctrl + Home", B: "Action Button", C: "End", D: "Phím Home" }, c: "D" },
        { s: "PowerPoint", q: "Câu 125: Thứ tự xuất hiện 3 đối tượng A (With Previous), B (With Previous), C (After Previous):", o: { A: "A, C, B", B: "A và B cùng lúc, sau đó đến C", C: "A, B, C", D: "A trước, B và C cùng lúc" }, c: "B" },
        { s: "PowerPoint", q: "Câu 126: Muốn chèn âm thanh hay phim vào Slide, ta dùng lệnh:", o: { A: "Insert/Comment", B: "Insert/Media", C: "Insert/Diagram", D: "Insert/Component" }, c: "B" },
        { s: "PowerPoint", q: "Câu 127: Dạng đuôi nào không phải đuôi file PowerPoint 2010?", o: { A: ".pptx", B: ".ppsm", C: ".pptm", D: ".pdf" }, c: "D" },
        { s: "PowerPoint", q: "Câu 128: Để định dạng một trang in trong PowerPoint 2010:", o: { A: "File/Print Review", B: "File/Page Setup", C: "File/Print", D: "Sai hết" }, c: "C" },
        { s: "PowerPoint", q: "Câu 129: Với Handout Master ta không thể làm gì?", o: { A: "Chỉnh sửa ngày tháng", B: "Chọn phông nền", C: "Cho hiện nội dung ghi chú trên slide khi in ra giấy", D: "Ẩn hiện tiêu đề" }, c: "C" },
        { s: "PowerPoint", q: "Câu 130: Có thể tạo Hyperlink đến các địa chỉ nào trong PowerPoint 2010?", o: { A: "Tập tin hình ảnh", B: "Tất cả đều đúng", C: "Tài liệu Excel, Word, Web...", D: "Các slide khác" }, c: "B" },
        { s: "PowerPoint", q: "Câu 131: Chức năng Zoom into the slide sử dụng ở chế độ hiển thị nào?", o: { A: "Slide Show", B: "Outline View", C: "Slide Sorter", D: "Reading View" }, c: "A" },
        { s: "PowerPoint", q: "Câu 132: Để tăng khoảng cách giữa các ký tự được chọn:", o: { A: "Home/Font/Character Spacing", B: "Text Shadow", C: "Underline", D: "Strikethrough" }, c: "A" },
        { s: "PowerPoint", q: "Câu 133: Đưa thêm Action Buttons vào slide hiện hành:", o: { A: "View/Action Button", B: "Slide Show/Action Buttons", C: "Insert/Shapes/Action Button", D: "Home/AutoShapes" }, c: "C" },
        { s: "PowerPoint", q: "Câu 134: PowerPoint 2010 có chế độ hiển thị nào?", o: { A: "Normal", B: "Notes Page", C: "Slide Sorter", D: "Tất cả A, B, C đều đúng" }, c: "D" },
        { s: "PowerPoint", q: "Câu 135: Cách nào không đúng để thêm Slide mới:", o: { A: "Ctrl+M", B: "Insert/New Slide", C: "Chọn mẫu Slide bấm Enter", D: "Bôi đen tất cả Ctrl+C và Ctrl+V" }, c: "D" },
        { s: "PowerPoint", q: "Câu 136: Muốn đánh dấu hay số đầu đoạn:", o: { A: "Insert/Bullets", B: "Format/Border", C: "Insert/Slide Number", D: "Home/Bullets and Numbering" }, c: "D" },
        { s: "PowerPoint", q: "Câu 137: Hiệu ứng xuất hiện của từng Slide dùng lệnh:", o: { A: "Transitions", B: "Slide Show", C: "Sai hết", D: "Đúng hết" }, c: "A" },
        { s: "PowerPoint", q: "Câu 138: Tổ hợp phím Ctrl + Shift + > có tác dụng:", o: { A: "Tăng kích thước văn bản", B: "Chữ nghiêng", C: "Giảm kích thước", D: "In đậm" }, c: "A" },
        { s: "PowerPoint", q: "Câu 139: Thao tác chọn File/Close dùng để:", o: { A: "Mở tập tin", B: "Thoát chương trình", C: "Đóng tập tin hiện tại", D: "Lưu tập tin" }, c: "C" },
        { s: "PowerPoint", q: "Câu 140: Chuyển màn hình đến slide đầu tiên khi đang trình chiếu:", o: { A: "Ctrl + Home", B: "Phím Home", C: "Action Button: Beginning", D: "Home" }, c: "B" },
        { s: "PowerPoint", q: "Câu 141: Định dạng chế độ trình chiếu không hiệu ứng:", o: { A: "Custom Show", B: "Setup Slide Show/Show Without Animation", C: "Show Without Narration", D: "Loop" }, c: "B" },
        { s: "PowerPoint", q: "Câu 142: Chọn câu sai khi thiết kế giáo án điện tử:", o: { A: "Không thể tạo chỉ số trên như trong MS-Word", B: "Dùng WordArt", C: "Copy từ Word sang", D: "Chèn biểu đồ" }, c: "A" },
        { s: "PowerPoint", q: "Câu 143: Mỗi trang trình diễn trong PowerPoint được gọi là:", o: { A: "Document", B: "Slide", C: "File", D: "Folder" }, c: "B" },
        { s: "PowerPoint", q: "Câu 144: Chức năng Record Slide Show:", o: { A: "Quay phim màn hình", B: "Ghi lại hoạt động trình chiếu lưu dưới dạng audio chèn trên slide", C: "Ghi thời gian", D: "Quay phim" }, c: "B" },
        { s: "PowerPoint", q: "Câu 145: Cách nào không đúng để xóa cột bảng biểu:", o: { A: "Chọn cột ấn Ctrl + X", B: "Click phải Delete Columns", C: "Chọn cột nhấn Delete", D: "Layout -> Delete Columns" }, c: "A" },
        { s: "PowerPoint", q: "Câu 146: Tạo hiệu ứng hình ảnh (nghiêng, 3D, bóng đổ):", o: { A: "Theme Styles", B: "Shape Effects", C: "Theme Styles", D: "Design/Themes" }, c: "B" },
        { s: "PowerPoint", q: "Câu 147: Chế độ hiển thị Outline view:", o: { A: "Văn bản không hình ảnh", B: "Hiệu chỉnh nhanh", C: "Sắp xếp đoạn văn", D: "Tất cả các phương án trên" }, c: "D" },
        { s: "PowerPoint", q: "Câu 148: Bộ công cụ Pen and laser pointer tools:", o: { A: "Pen, Laser Pointer, Highlighter và Eraser", B: "Đủ màu", C: "Pen, Laser", D: "Pen" }, c: "A" },
        { s: "PowerPoint", q: "Câu 149: Chế độ Reading View:", o: { A: "Tất cả đúng", B: "Chiếu toàn màn hình với hiệu ứng sinh động", C: "Báo cáo", D: "Diễn tập" }, c: "B" },
        { s: "PowerPoint", q: "Câu 150: Hiện tất cả các soạn thảo chồng lên nhau:", o: { A: "Cascade", B: "Switch Windows", C: "New Windows", D: "Arrange All" }, c: "A" },
        { s: "PowerPoint", q: "Câu 151: Chế độ Slide Sorter:", o: { A: "Hiển thị các slide dưới dạng hình nhỏ", B: "Xem trước khi in", C: "Diễn tập", D: "Toàn màn hình" }, c: "A" },
        { s: "PowerPoint", q: "Câu 152: Chạy slide có nhúng Macros ở chế độ:", o: { A: "Slide Show", B: "Reading View", C: "Outline View", D: "Normal View" }, c: "A" },
        { s: "PowerPoint", q: "Câu 153: Tô nền cho từng Slide:", o: { A: "Design/Format Background/Hide background graphic", B: "Fill Color", C: "Cả A và B đúng", D: "Sai" }, c: "A" },
        { s: "PowerPoint", q: "Câu 154: Thay đổi vị trí slide:", o: { A: "Outline View", B: "Slide Sorter", C: "Normal View", D: "Tất cả đều đúng" }, c: "D" },
        { s: "PowerPoint", q: "Câu 155: Ở chế độ Slide Show không dùng được:", o: { A: "Zoom into the slide", B: "Macros", C: "Black show", D: "See all slides" }, c: "A" },
        { s: "PowerPoint", q: "Câu 156: Khởi động PowerPoint 2010:", o: { A: "Start/Search", B: "Double click Desktop", C: "Start/Program", D: "Câu A và C đúng" }, c: "D" },
        { s: "PowerPoint", q: "Câu 157: Tạo bản trình diễn mới từ:", o: { A: "Trình diễn có sẵn", B: "Blank", C: "Design Template", D: "Tất cả phương án trên" }, c: "D" },
        { s: "PowerPoint", q: "Câu 158: Ở chế độ Slide Show:", o: { A: "Dùng Pen viết lên slide", B: "Highlighter", C: "Thấy Taskbar", D: "Tất cả đúng" }, c: "A" },
        { s: "PowerPoint", q: "Câu 159: Chèn đối tượng Windows Media Player:", o: { A: "Insert/Media/Video", B: "Sai", C: "Developer/Controls/More Controls/Windows Media Player", D: "Kéo thả" }, c: "C" },
        { s: "PowerPoint", q: "Câu 160: Tổ hợp phím Ctrl + B:", o: { A: "Gạch chân", B: "In nghiêng", C: "In đậm", D: "Tăng size" }, c: "C" },
        { s: "PowerPoint", q: "Câu 161: Thiết lập Handout:", o: { A: "Notes Master", B: "Normal", C: "Handout Master", D: "Slide Master" }, c: "C" },
        { s: "PowerPoint", q: "Câu 162: Đi đến slide cuối cùng, cách nào không đúng:", o: { A: "Phím End", B: "PgDn liên tục", C: "PgUp liên tục", D: "Ctrl + End" }, c: "C" },
        { s: "PowerPoint", q: "Câu 163: Slide 2 xuất hiện sau Slide 1 5 giây:", o: { A: "Chọn Slide 1, Transition, After 00:05", B: "Slide 2, Transition, After 05:00", C: "Slide 2, Transition, After 00:00:05", D: "Slide 1, Transition, After 00:00:05" }, c: "D" },
        { s: "PowerPoint", q: "Câu 164: Cách nào không dùng để trình diễn:", o: { A: "From Current Slide", B: "Reading View", C: "From Beginning", D: "Outline View" }, c: "D" },
        { s: "PowerPoint", q: "Câu 165: Thiết lập Notes Master:", o: { A: "Slide Master", B: "Notes Master", C: "Normal", D: "Handout Master" }, c: "B" },
        { s: "PowerPoint", q: "Câu 166: Lệnh căn lề không đúng:", o: { A: "Ctrl + E", B: "Ctrl + K", C: "Ctrl + L", D: "Ctrl + R" }, c: "B" },
        { s: "PowerPoint", q: "Câu 167: Bấm Delete tại Slide hiện hành:", o: { A: "Không thực hiện", B: "Thêm slide", C: "Thêm slide hiện thời", D: "Xóa Slide" }, c: "D" },
        { s: "PowerPoint", q: "Câu 168: Sử dụng Hyperlink cho phép liên kết đến:", o: { A: "Chỉ ổ đĩa", B: "Chỉ Slide", C: "Chỉ Web", D: "Tất cả tập tin, slide và trang web" }, c: "D" },
        { s: "PowerPoint", q: "Câu 169: Tổ hợp phím Ctrl + I:", o: { A: "In đậm", B: "In nghiêng", C: "Tăng size", D: "Gạch chân" }, c: "B" },
        { s: "PowerPoint", q: "Câu 170: Đối tượng Windows Media Player hoạt động cần:", o: { A: "Đường dẫn chính xác", B: "Chạy song song", C: "Tương thích", D: "Đường dẫn chính xác và tương thích" }, c: "D" },
        { s: "PowerPoint", q: "Câu 171: Tổ hợp phím Ctrl + U:", o: { A: "Gạch chân", B: "Tăng size", C: "In đậm", D: "In nghiêng" }, c: "A" },
        { s: "PowerPoint", q: "Câu 172: Chèn ký hiệu vào Slide:", o: { A: "Component", B: "Symbol", C: "Comment", D: "Diagram" }, c: "B" },
        { s: "PowerPoint", q: "Câu 173: Thêm hiệu ứng âm thanh, cách nào không đúng:", o: { A: "Insert/Media/Video", B: "Kéo thả", C: "Click phải kéo thả", D: "Insert/Media/Audio" }, c: "A" },
        { s: "PowerPoint", q: "Câu 174: Tác dụng Handout Master:", o: { A: "Chia slide", B: "Định dạng trang in", C: "Cây thư mục", D: "Dạng in" }, c: "B" },
        { s: "PowerPoint", q: "Câu 175: Đối tượng Windows Media Player hoạt động cần:", o: { A: "Đường dẫn", B: "Chạy song song", C: "Tương thích", D: "Đường dẫn chính xác và tương thích" }, c: "D" },
        { s: "PowerPoint", q: "Câu 176: Vẽ hình minh họa trên màn hình trình diễn, cách không đúng:", o: { A: "Laser Pointer", B: "Ctrl+P", C: "Pen", D: "Highlighter" }, c: "A" },
        { s: "PowerPoint", q: "Câu 177: Thiết lập khoảng cách dòng trong Word:", o: { A: "Clipboard", B: "Font", C: "Paragraph", D: "Styles" }, c: "C" },
        { s: "PowerPoint", q: "Câu 178: Tổ hợp phím Ctrl + U:", o: { A: "Gạch chân", B: "Tăng size", C: "In đậm", D: "In nghiêng" }, c: "A" },
        { s: "PowerPoint", q: "Câu 179: Chèn ký hiệu vào Slide:", o: { A: "Component", B: "Symbol", C: "Diagram", D: "Comment" }, c: "B" },
        { s: "PowerPoint", q: "Câu 180: Thêm hiệu ứng âm thanh, cách không đúng:", o: { A: "Video", B: "Kéo thả trái", C: "Kéo thả phải", D: "Audio" }, c: "A" },
        { s: "PowerPoint", q: "Câu 181: PowerPoint có thể làm gì:", o: { A: "Handouts", B: "Tất cả phương án", C: "Trình diễn", D: "In overhead" }, c: "B" },
        { s: "PowerPoint", q: "Câu 182: Tăng khoảng cách dòng trong PowerPoint:", o: { A: "Line Spacing", B: "Column", C: "Decrease", D: "Increase" }, c: "A" },
        { s: "PowerPoint", q: "Câu 183: Chuyển sang trình chiếu khác đang mở:", o: { A: "Switch Windows", B: "New", C: "Arrange", D: "Cascade" }, c: "A" },
        { s: "PowerPoint", q: "Câu 184: Lợi ích của Template:", o: { A: "Giảm thời gian thiết kế", B: "Hạn chế lỗi", C: "Giảm thời gian", D: "Thiết định sẵn" }, c: "A" },
        { s: "PowerPoint", q: "Câu 185: Loại bỏ slide khỏi quá trình trình chiếu không phải xóa, cách không đúng:", o: { A: "Hide Slide", B: "Slide Show/Hide", C: "Outline Hide", D: "Normal Hide" }, c: "C" },
        { s: "PowerPoint", q: "Câu 186: Chế độ hiển thị nào không phải của Slide:", o: { A: "Slide Sorter", B: "Master Views", C: "Reading View", D: "Normal" }, c: "B" },
        { s: "PowerPoint", q: "Câu 187: Làm đối tượng chuyển động theo hướng mong muốn:", o: { A: "Motion Paths", B: "Emphasis", C: "Exit", D: "Entrance" }, c: "A" },
        { s: "PowerPoint", q: "Câu 188: Tổ hợp phím Ctrl + I:", o: { A: "In đậm", B: "In nghiêng", C: "Tăng size", D: "Gạch chân" }, c: "B" },
        { s: "PowerPoint", q: "Câu 189: Thiết lập Slide Master:", o: { A: "Slide Master", B: "Normal", C: "Handout Master", D: "Notes Master" }, c: "A" },
        { s: "PowerPoint", q: "Câu 190: Tạo dự án theo mẫu có sẵn:", o: { A: "File/Open", B: "View", C: "File/New", D: "Tất cả" }, c: "C" },
        { s: "PowerPoint", q: "Câu 191: In 6 slide khổ A4 thẳng:", o: { A: "6 Slides Vertical & Portrait", B: "Horizontal & Landscape", C: "Vertical & Landscape", D: "Horizontal & Portrait" }, c: "A" },
        { s: "PowerPoint", q: "Câu 192: Chọn tất cả slide từ vị trí đang chọn đến cuối, cách không đúng:", o: { A: "Shift + mũi tên xuống", B: "Shift + End", C: "Ctrl + click từng cái", D: "Shift + PgUp" }, c: "C" },
        { s: "PowerPoint", q: "Câu 193: Hiệu chỉnh cho tất cả slide chung một màu nền:", o: { A: "Color/Apply to All", B: "Background Style/Apply to All", C: "Design/Color", D: "Theme" }, c: "B" },
        { s: "PowerPoint", q: "Câu 194: Cách không dùng khi trình diễn:", o: { A: "Reading View", B: "Outline View", C: "From Current Slide", D: "From Beginning" }, c: "B" },
        { s: "PowerPoint", q: "Câu 195: Ở chế độ Slide Show không làm được gì:", o: { A: "Chạy Macros", B: "Highlighter", C: "Tất cả đúng", D: "Dùng Pen viết" }, c: "C" },
        { s: "PowerPoint", q: "Câu 196: Ghi lại hoạt động trình chiếu điều chỉnh thời gian:", o: { A: "Set Up", B: "Record Slide Show", C: "Hide Slide", D: "Rehearse Timings" }, c: "D" },
        { s: "PowerPoint", q: "Câu 197: Đưa nội dung văn bản về bên trái:", o: { A: "Ctrl + R", B: "Ctrl + K", C: "Ctrl + E", D: "Ctrl + L" }, c: "D" },

        // ================= PHẦN EXCEL (198 - 337) =================
        { s: "Excel", q: "Câu 198: Trong Excel 2010, để thay đổi hiển thị các cột của bảng trụ xoay (Pivot Table) ta thực hiện:", o: { A: "PivotTable Field List, thay đổi các giá trị trong Report Filter", B: "PivotTable Field List, thay đổi các giá trị trong Rows Lables", C: "PivotTable Field List, thay đổi các giá trị trong Column Lables", D: "PivotTable Field List, thay đổi các giá trị trong Values" }, c: "C" },
        { s: "Excel", q: "Câu 199: Trong Excel 2010, chọn phát biểu đúng:", o: { A: "Lọc dữ liệu nâng cao", B: "Lọc dữ liệu nâng cao cho phép sao chép lọc dữ liệu được sang vùng khác", C: "Lọc dữ liệu nâng cao chỉ cần 1 điều kiện", D: "Lọc dữ liệu nâng cao không cần điều kiện lọc" }, c: "B" },
        { s: "Excel", q: "Câu 200: Trong Excel 2010, để đưa 1 thông báo khi chọn ô có kiểm tra dữ liệu nhập, ta thao tác:", o: { A: "Data Validation/Settings/Validation criteria", B: "Data Validation/Settings/ Circle invalid data", C: "Data Validation/Settings/Input Massage", D: "Data Validation/Settings/ Error Alert" }, c: "C" },
        { s: "Excel", q: "Câu 201: Trong Excel 2010, để tạo một cảnh báo sau khi nhập sai dữ liệu ta thao tác:", o: { A: "Data Validation/Settings/Input Masage", B: "Data Validation/Settings/ Error Alert", C: "Data Validation/Settings/Circle invalid data", D: "Data Validation/Settings/Validation criteria" }, c: "B" },
        { s: "Excel", q: "Câu 202: Trong Excel 2010 cấu trúc (Giá trị bạn muốn tra cứu, dải ô mà bạn muốn tìm giá trị, số cột trong dải ô chứa giá trị trả về,...)", o: { A: "Hlookup", B: "Vlookup", C: "Lookup", D: "SUMIF" }, c: "B" },
        { s: "Excel", q: "Câu 203: Trong Excel 2010, để cập nhật liên kết đến Sheet 3, ta thao tác:", o: { A: "Insert/Links/Hyperlink/Remove Link", B: "Insert/Links/Hyperlink/Create New Document", C: "Insert/Links/Hyperlink/E-mail Address", D: "Insert/Links/Hyperlink/Place in This Document" }, c: "D" },
        { s: "Excel", q: "Câu 204: Trong Excel 2010, để xóa liên kết trong ô, ta thao tác:", o: { A: "Insert/Links/Hyperlink/Remove Link", B: "Insert/Links/Hyperlink/Place in This Document", C: "Insert/Links/Hyperlink/Create New Document", D: "Insert/Links/Hyperlink/E-mail Address" }, c: "A" },
        { s: "Excel", q: "Câu 205: Trong Excel 2010, để hiển thị các cửa sổ bảng tính có trong bảng tính:", o: { A: "View/Window/Reset Window Position", B: "View/Window/Switch Window", C: "View/Window/View Side by Side", D: "View/Window/New Window" }, c: "D" },
        { s: "Excel", q: "Câu 206: Trong Excel 2010 để hiển thị đường kẻ dưới bảng tính, ta thao tác?", o: { A: "File/Options/Advanced/Show Formula bar", B: "File/Options/Advanced/Show gridlines", C: "File/Options/Advanced/Show Insert Option Button", D: "File/Options/Advanced/Show Paste Option button" }, c: "B" },
        { s: "Excel", q: "Câu 207: Trong Excel 2010, để áp dụng định dạng thời gian có sẵn ta thực hiện:", o: { A: "Home/Number/Accounting", B: "Home/Number/Time", C: "Home/Number/Currency", D: "Home/Number/Number" }, c: "B" },
        { s: "Excel", q: "Câu 208: Trong Excel 2010, ý nghĩa của báo lỗi #N/A?", o: { A: "Lỗi sai tên hàm", B: "Lỗi sai giá trị", C: "Lỗi dữ liệu", D: "Lỗi chia cho 0" }, c: "C" },
        { s: "Excel", q: "Câu 209: Trong Excel 2010 để hiển thị đường kẻ dưới bảng tính, ta thao tác?", o: { A: "File/Options/Advanced/Show Formula bar", B: "File/Options/Advanced/Show gridlines", C: "File/Options/Advanced/Show Insert Option Button", D: "File/Options/Advanced/Show Paste Option button" }, c: "B" },
        { s: "Excel", q: "Câu 210: Trong Excel 2010, để áp dụng định dạng thời gian có sẵn ta thực hiện:", o: { A: "Home/Number/Accounting", B: "Home/Number/Time", C: "Home/Number/Currency", D: "Home/Number/Number" }, c: "B" },
        { s: "Excel", q: "Câu 211: Trong Excel 2010, ý nghĩa của báo lỗi #N/A?", o: { A: "Lỗi sai tên hàm", B: "Lỗi sai giá trị", C: "Lỗi dữ liệu", D: "Lỗi chia cho 0" }, c: "C" },
        { s: "Excel", q: "Câu 212: Trong Excel 2010, để sử dụng các mẫu (template) có sẵn của Microsoft?", o: { A: "File/Print", B: "File/Save", C: "File/Options", D: "File/New" }, c: "D" },
        { s: "Excel", q: "Câu 213: Trong Excel 2010, để sao chép biểu thức của ô, sau khi sao chép ô, ta chọn kiểu dán:", o: { A: "Formats", B: "Formulas", C: "Comments", D: "Values" }, c: "B" },
        { s: "Excel", q: "Câu 214: Trong Excel 2010, Hàm tính tích số là:", o: { A: "SUM()", B: "PRODUCT()", C: "COUNTA()", D: "SUMIF()" }, c: "B" },
        { s: "Excel", q: "Câu 215: Trong Excel 2010, ý nghĩa của hàm NOMINAL() là gì?", o: { A: "Tính tổng các giá trị", B: "Tính lãi suất thực tế hàng năm", C: "Trả về lãi suất danh nghĩa hàng năm", D: "Trả về mức chiết khấu" }, c: "C" },
        { s: "Excel", q: "Câu 216: Trong Excel 2010, A1=11, A2=12, kết quả công thức =AND(VALUE(A1)>10, VALUE(A2)<5)", o: { A: "FALSE", B: "#N/A", C: "#VALUE", D: "TRUE" }, c: "A" },
        { s: "Excel", q: "Câu 217: Trong Excel 2010, để chèn biểu đồ kết hợp dạng cột và dạng đường, ta chọn:", o: { A: "Insert/Charts/Bar", B: "Insert/Charts/Combo", C: "Insert/Charts/Column", D: "Insert/Charts/Line" }, c: "B" },
        { s: "Excel", q: "Câu 218: Trong Excel 2010, cho hàm SUBTOTAL(9, ref1, [ref2],..), tham số 9 có ý nghĩa gì?", o: { A: "Hàm AVERAGE()", B: "Hàm SUM()", C: "Hàm COUNT()", D: "Hàm MAX()" }, c: "B" },
        { s: "Excel", q: "Câu 219: Trong Excel 2010, chọn phát biểu sai về Validation:", o: { A: "Khi nhập dữ liệu ngoài vùng kiểm tra...", B: "Thông báo lỗi Stop không cho phép nhận giá trị...", C: "Thông báo lỗi Information cho phép nhận giá trị...", D: "Thông báo lỗi Warning không cho phép nhận giá trị dù nhập ngoài vùng kiểm tra" }, c: "D" },
        { s: "Excel", q: "Câu 220: Trong Excel 2010, Kết quả của hàm ODD(225)?", o: { A: "226", B: "15", C: "16", D: "225" }, c: "D" },
        { s: "Excel", q: "Câu 221: Trong Excel 2010, để chèn thêm trường vào đầu trang tính, ta thao tác:", o: { A: "Insert/Text/WordArt", B: "Insert/Text/Text box", C: "Insert/Text/Footer", D: "Insert/Text/Header" }, c: "D" },
        { s: "Excel", q: "Câu 222: Trong Excel 2010, để thay đổi tỉ lệ hiển thị đường kẻ trục hoành của biểu đồ hình cột, ta thao tác:", o: { A: "Layout/Axes/Vertical Axes", B: "Layout/Axes/Horizontal Girdlines", C: "Layout/Axes/Vertical Girdlines", D: "Layout/Axes/Horizontal Axes" }, c: "B" },
        { s: "Excel", q: "Câu 223: Trong Excel 2010, để sửa 1 siêu liên kết được chọn ta thao tác:", o: { A: "Format Cells", B: "Remove hyperlink", C: "Edit HyperLink", D: "Define Name" }, c: "C" },
        { s: "Excel", q: "Câu 224: Trong Excel 2010, để sửa tiêu đề kiểm tra dữ liệu từ chữ sang số:", o: { A: "Data Validation/Settings/Validation criteria/Data", B: "Data Validation/Settings/Validation criteria/Allow", C: "Data Validation/Settings/Validation criteria/Minimum", D: "Data Validation/Settings/Validation criteria/Maximum" }, c: "B" },
        { s: "Excel", q: "Câu 225: Trong Excel 2010, để tạo sao chép giá trị của ô:", o: { A: "Value", B: "Comments", C: "Formats", D: "Formulas" }, c: "A" },
        { s: "Excel", q: "Câu 226: Trong Excel 2010, ý nghĩa của hàm DCOUNTA()?", o: { A: "Đếm ô không trống", B: "Giá trị tối đa", C: "Đếm ô chứa số", D: "Trích từ cơ sở dữ liệu bản ghi khớp tiêu chí" }, c: "A" },
        { s: "Excel", q: "Câu 227: Trong Excel 2010, để hoán đổi giữa giá trị cột và dòng trong biểu đồ:", o: { A: "Select Data/Edit/Series values", B: "Select Data/Add/Series values", C: "Switch Row/Column", D: "Select Data/Edit/column" }, c: "C" },
        { s: "Excel", q: "Câu 228: Trong Excel 2010, sau khi thay đổi dữ liệu nguồn, kết quả bảng trụ:", o: { A: "Tự động cập nhật", B: "Bị xóa", C: "Nhập kết quả", D: "Không tự cập nhật kết quả" }, c: "D" },
        { s: "Excel", q: "Câu 229: Trong Excel 2010, để lần dấu thay đổi chi tiết trong bảng tính:", o: { A: "List changes on a new sheet", B: "Review/Changes/Accept/Reject", C: "Highlight changes on screen", D: "Review/Comments" }, c: "C" },
        { s: "Excel", q: "Câu 230: Trong Excel 2010, ô A2=EDATE(\"15/7/2014\",4) cho kết quả:", o: { A: "19/7/2017", B: "15/7/2017", C: "15/7/2021", D: "15/11/2014" }, c: "D" },
        { s: "Excel", q: "Câu 231: Để thiết lập thước kẻ centimet trong Word:", o: { A: "Customize", B: "Proofing", C: "Advanced", D: "Display" }, c: "C" },
        { s: "Excel", q: "Câu 232: Trong Word 2010, File/New/Templates có tác dụng:", o: { A: "Biểu đồ", B: "Thư", C: "Hình nền", D: "Tạo mẫu văn bản" }, c: "D" },
        { s: "Excel", q: "Câu 233: Trong Excel 2010, thiết lập lại thanh công cụ:", o: { A: "Customize Ribbon", B: "General", C: "Advance", D: "Quick Access Toolbar" }, c: "A" },
        { s: "Excel", q: "Câu 234: Xem thông tin thuộc tính bảng tính hiện hành:", o: { A: "Show Fewer Properties", B: "Advanced Properties", C: "Show Document Panel", D: "Show All Properties" }, c: "B" },
        { s: "Excel", q: "Câu 235: Phát biểu đúng về thuộc tính che giấu công thức:", o: { A: "Cho phép chỉnh sửa", B: "Cần kích hoạt Format Cells/Protection/Locked", C: "Không cho người khác xem công thức", D: "Không cần đặt mật khẩu Protect Sheet" }, c: "C" },
        { s: "Excel", q: "Câu 236: Trong Excel 2010, Phím tắt hiện cột bảng tính bị ẩn là?", o: { A: "Ctrl+Shift+9", B: "Ctrl+Shift+0", C: "Ctrl+9", D: "Ctrl+0" }, c: "B" },
        { s: "Excel", q: "Câu 237: Thay đổi thông tin tác giả bảng tính:", o: { A: "Last Modified", B: "Subject", C: "Last Modified By", D: "Authors" }, c: "D" },
        { s: "Excel", q: "Câu 238: Chọn phát biểu đúng về Header/Footer:", o: { A: "Bắt đầu từ số 1", B: "Chỉ áp dụng trang tính chọn", C: "Header cho phép đánh số trang bắt đầu từ số bất kỳ", D: "Không hiển thị" }, c: "C" },
        { s: "Excel", q: "Câu 239: Hoán đổi giá trị cột và dòng trong biểu đồ:", o: { A: "Remove", B: "Add", C: "Series values", D: "Switch Row/Column" }, c: "D" },
        { s: "Excel", q: "Câu 240: Ô A1=\"123\", để A2 trả về giá trị số:", o: { A: "VALUE(A1)", B: "CHAR(A1)", C: "LEFT(A1)", D: "FIXED(A1)" }, c: "A" },
        { s: "Excel", q: "Câu 241: Hlookup có ý nghĩa gì?", o: { A: "Tra cứu vec-tơ", B: "Tra cứu hàng trên cùng một mảng và trả về giá trị", C: "Tra cứu cột thứ nhất", D: "Tổng số cột" }, c: "B" },
        { s: "Excel", q: "Câu 242: Thêm trục thứ 2 vào biểu đồ:", o: { A: "Add Chart Element", B: "Chart Styles", C: "Change Chart Type", D: "Select Data" }, c: "C" },
        { s: "Excel", q: "Câu 243: Chọn phát biểu đúng về liên kết Word và Excel:", o: { A: "Có thể liên kết dữ liệu giữa Word và Excel", B: "Chỉ từ Word sang Excel", C: "Chỉ từ Excel sang Word", D: "Không thể" }, c: "A" },
        { s: "Excel", q: "Câu 244: Tệp tin XML có dạng:", o: { A: "*.xml", B: "*.docx", C: "*.xlsx", D: "*.csv" }, c: "A" },
        { s: "Excel", q: "Câu 245: Chọn phát biểu đúng:", o: { A: "Sắp xếp nhiều cột, không đổi dòng", B: "Chỉ sắp xếp theo giá trị", C: "Chỉ tăng dần", D: "Có thể sắp xếp theo màu chữ" }, c: "D" },
        { s: "Excel", q: "Câu 246: Tạo mẫu theo yêu cầu thuận tiện nhất:", o: { A: "Nhập vào xlsx rồi xóa", B: "Tham chiếu từ doc", C: "Tìm mẫu gần giống chỉnh sửa", D: "Tạo mới" }, c: "C" },
        { s: "Excel", q: "Câu 247: Đổi tên vùng ô:", o: { A: "Delete", B: "Edit", C: "Filter", D: "New" }, c: "B" },
        { s: "Excel", q: "Câu 248: Tạo biểu đồ kết hợp cột và đường yêu cầu dữ liệu:", o: { A: "Biểu đồ cột", B: "Dữ liệu cho biểu đồ cột và đường", C: "1 cột", D: "Biểu đồ đường" }, c: "B" },
        { s: "Excel", q: "Câu 249: Đặt tiêu chí dữ liệu nhập:", o: { A: "Text to Column", B: "Remove Duplicates", C: "Data Validation", D: "Consolidate" }, c: "C" },
        { s: "Excel", q: "Câu 250: Ẩn ghi chú được chọn:", o: { A: "Show All Comments", B: "Delete", C: "Edit Comment", D: "Hide Comments" }, c: "D" },
        { s: "Excel", q: "Câu 251: Ý nghĩa hộp thoại Highlight Changes:", o: { A: "Làm nổi những thay đổi dữ liệu mới lên màn hình", B: "Tắt tính năng làm nổi", C: "Làm nổi tất cả", D: "Tắt tính năng" }, c: "A" },
        { s: "Excel", q: "Câu 252: Chèn số trang vào đầu trang tính:", o: { A: "Go To Header/Page Number", B: "Go To Footer/Page Number", C: "Header/Number of Page", D: "Footer/Number of Page" }, c: "A" },
        { s: "Excel", q: "Câu 253: Hiển thị thanh công thức:", o: { A: "Show gridlines", B: "Show Formula bar", C: "Insert Option", D: "Paste Option" }, c: "B" },
        { s: "Excel", q: "Câu 254: Đặt mật khẩu cho sheet hiện hành:", o: { A: "Protect Workbook", B: "Protect Workbook", C: "Review/Protect Sheet", D: "Share Workbook" }, c: "C" },
        { s: "Excel", q: "Câu 255: Đặt mật khẩu khi mở bảng tính:", o: { A: "Manage Versions", B: "Browser View Options", C: "Check for Issues", D: "Protect Workbook" }, c: "D" },
        { s: "Excel", q: "Câu 256: Bỏ chọn dấu công thức của ô:", o: { A: "Review/Protect Sheet", B: "Format cells/Protection/Bỏ chọn Hidden", C: "Protect Workbook", D: "Share Workbook" }, c: "B" },
        { s: "Excel", q: "Câu 257: Tạo định dạng, kiểu cách cho vùng ô:", o: { A: "Custom Styles", B: "New Rules", C: "Cell Styles/New Cell Styles", D: "Merge Styles" }, c: "C" },
        { s: "Excel", q: "Câu 258: Hàm lấy ngày, tháng, năm hiện hành:", o: { A: "TODAY()", B: "SUM()", C: "PRODUCT()", D: "COUNTA()" }, c: "A" },
        { s: "Excel", q: "Câu 259: Tại ô B7=COUNTA(B2:B6) với 5 ô đều có dữ liệu:", o: { A: "5", B: "1", C: "4", D: "0" }, c: "A" },
        { s: "Excel", q: "Câu 260: Lọc dữ liệu nâng cao:", o: { A: "Lọc ra 5 kết quả sao chép đến A9", B: "Lọc 5 kết quả dòng còn lại ẩn", C: "Lọc 3 kết quả sao chép đến A9", D: "Lọc 3 kết quả dòng ẩn" }, c: "C" },
        { s: "Excel", q: "Câu 261: Kết quả của hàm N(\"123\"):", o: { A: "TRUE", B: "0", C: "FALSE", D: "123" }, c: "B" },
        { s: "Excel", q: "Câu 262: Lưu lại như một mẫu để sử dụng sau này:", o: { A: "*.pdf", B: "*.csv", C: "*.xlsx", D: "*.xltx" }, c: "D" },
        { s: "Excel", q: "Câu 263: Tệp tin có phần mở rộng *.xltx là:", o: { A: "Tệp tin mẫu cho phép nhập dữ liệu", B: "Cơ sở dữ liệu", C: "Định dạng văn bản", D: "Siêu văn bản" }, c: "A" },
        { s: "Excel", q: "Câu 264: Phát biểu sai khi nói về mẫu (Template):", o: { A: "Hỗ trợ tính toán nhanh", B: "Định dạng xltx", C: "Chỉnh sửa theo ý muốn", D: "Không thể thay đổi mẫu có sẵn" }, c: "D" },
        { s: "Excel", q: "Câu 265: Áp dụng định dạng cho vùng các ô:", o: { A: "Format as Table", B: "Conditional Formatting", C: "Cells Styles", D: "Insert" }, c: "A" },
        { s: "Excel", q: "Câu 266: A1=\"1\", A2=\"0\", A3=OR(A1,A2) kết quả trả về:", o: { A: "#VALUE", B: "#N/A", C: "FALSE", D: "TRUE" }, c: "D" },
        { s: "Excel", q: "Câu 267: Chọn câu sai khi nói về tham chiếu 3-D:", o: { A: "Hàm SUMIF() có thể tham chiếu 3-D", B: "Tiện dụng tham chiếu trang tính cùng mẫu", C: "Tham chiếu cùng ô trên nhiều trang", D: "Hàm SUM() tham chiếu 3-D" }, c: "A" },
        { s: "Excel", q: "Câu 268: Tính tổng các kết quả sau khi lọc dữ liệu:", o: { A: "SUMIF()", B: "SQRT()", C: "SUBTOTAL()", D: "SUM()" }, c: "C" },
        { s: "Excel", q: "Câu 269: Mẫu biểu đồ hình cột xếp chồng:", o: { A: "3-D Cone", B: "Stack Column", C: "Clustered Column", D: "100% Stacked Column" }, c: "B" },
        { s: "Excel", q: "Câu 270: Tính năng Data Validation có tác dụng gì:", o: { A: "Hạn chế loại dữ liệu nhập hoặc giá trị", B: "Gợi nhớ ký tự", C: "Kiểm tra ngữ pháp", D: "Gợi nhớ cú pháp" }, c: "A" },
        { s: "Excel", q: "Câu 271: A1=12:53:13, A2=IF(HOUR(A1>12), \"Đúng\", \"Sai\") cho kết quả:", o: { A: "True", B: "Sai", C: "False", D: "Đúng" }, c: "D" },
        { s: "Excel", q: "Câu 272: Hàm Product() thay thế cho phép toán:", o: { A: "Chia", B: "Trừ", C: "Nhân", D: "Cộng" }, c: "C" },
        { s: "Excel", q: "Câu 273: Chọn phát biểu đúng về biểu đồ:", o: { A: "Có 6 kiểu", B: "Tùy chỉnh theo ý muốn", C: "Chỉ dùng mẫu", D: "Có 5 kiểu" }, c: "B" },
        { s: "Excel", q: "Câu 274: Chọn phát biểu đúng về liên kết:", o: { A: "Xóa tệp bất kỳ", B: "Chỉ liên kết ô, vùng ô", C: "Chỉ giữa các bảng tính", D: "Mở ứng dụng khác" }, c: "C" },
        { s: "Excel", q: "Câu 275: Liên kết dữ liệu từ Word sang Excel:", o: { A: "Paste Special/Paste", B: "Paste Special/Paste Link", C: "Functions", D: "Values" }, c: "B" },
        { s: "Excel", q: "Câu 276: Lọc dữ liệu trong vùng chọn:", o: { A: "Data Validation", B: "Group", C: "Remove Duplicates", D: "Filter/Chọn giá trị" }, c: "D" },
        { s: "Excel", q: "Câu 277: Phím tắt hiển thị công thức:", o: { A: "Shift + -", B: "Ctrl + Shift + ~", C: "Ctrl + `", D: "Ctrl + -" }, c: "C" },
        { s: "Excel", q: "Câu 278: Hiển thị thay đổi dữ liệu mới:", o: { A: "Show All Comments", B: "Accept/Reject", C: "Formular Bar", D: "Highlight Changes" }, c: "D" },
        { s: "Excel", q: "Câu 279: Thay đổi kiểu biểu đồ trên cùng tập dữ liệu:", o: { A: "Add Chart Element", B: "Chart Styles", C: "Change Chart Type", D: "Select Data" }, c: "C" },
        { s: "Excel", q: "Câu 280: Chọn phát biểu sai về sắp xếp:", o: { A: "Sắp xếp cùng lúc 1 cột", B: "Nhiều cột", C: "Tăng dần", D: "Dữ liệu dòng thay đổi" }, c: "A" },
        { s: "Excel", q: "Câu 281: Bật/tắt formula autocomplete:", o: { A: "General", B: "Advance", C: "Proofing", D: "Formulas" }, c: "D" },
        { s: "Excel", q: "Câu 282: Tìm kiếm, thay thế dữ liệu:", o: { A: "Ctrl+C", B: "Ctrl+S", C: "Ctrl+F", D: "Ctrl+H" }, c: "D" },
        { s: "Excel", q: "Câu 283: Mở rộng vùng chọn về ô đầu tiên:", o: { A: "Shift + End", B: "Ctrl + Shift + Home", C: "Ctrl + Home", D: "Ctrl + Shift + End" }, c: "B" },
        { s: "Excel", q: "Câu 284: Mẫu (Template) có chức năng gì:", o: { A: "Nhập liệu ngay không cần thao tác hàng cột", B: "Khó thao tác", C: "Chỉnh sửa giao diện", D: "Định dạng xlxs" }, c: "A" },
        { s: "Excel", q: "Câu 285: Phát biểu đúng về Mẫu:", o: { A: "Mặc định không tạo được", B: "Không thay đổi mật khẩu", C: "Thay đổi sau khi nhập", D: "Mẫu có thể thay đổi theo yêu cầu" }, c: "D" },
        { s: "Excel", q: "Câu 286: Phát biểu đúng khi sử dụng tên vùng ô:", o: { A: "Không dùng vào công thức", B: "Dùng ký tự đặc biệt", C: "Có thể sử dụng vào công thức", D: "Không thể đặt giống nhau" }, c: "C" },
        { s: "Excel", q: "Câu 287: A1=PRODUCT(12,10)/0 cho kết quả:", o: { A: "#DIV/0", B: "120", C: "12", D: "#VALUE" }, c: "A" },
        { s: "Excel", q: "Câu 288: Xóa định dạng có điều kiện:", o: { A: "New Rules", B: "Clear Contents", C: "Manager Rules", D: "Clear Rules" }, c: "D" },
        { s: "Excel", q: "Câu 289: Xóa tên cho vùng ô:", o: { A: "Edit", B: "New", C: "Delete", D: "Filter" }, c: "C" },
        { s: "Excel", q: "Câu 290: Ẩn cột B của bảng tính:", o: { A: "Delete", B: "Hide", C: "UnHide", D: "Clear Content" }, c: "B" },
        { s: "Excel", q: "Câu 291: A1=\"CH-05\", A2=RIGHT(A1,2) cho kết quả:", o: { A: "5", B: "\"5\"", C: "\"05\"", D: "105" }, c: "C" },
        { s: "Excel", q: "Câu 292: Thay đổi tỉ lệ trục tung biểu đồ cột:", o: { A: "Horizontal Axes", B: "Vertical Girdlines", C: "Horizontal Girdlines", D: "Vertical Axes" }, c: "D" },
        { s: "Excel", q: "Câu 293: Tạo liên kết đến ô bảng tính khác:", o: { A: "Cell Reference", B: "Create New Document", C: "Existing File or WebPage", D: "Place in This Document" }, c: "A" },
        { s: "Excel", q: "Câu 294: Tạo thứ tự sắp xếp theo yêu cầu:", o: { A: "Custom List", B: "Nhập giá trị", C: "Add Level", D: "Tăng dần" }, c: "A" },
        { s: "Excel", q: "Câu 295: Chỉnh sửa ghi chú được chọn:", o: { A: "Protect Sheet", B: "New Comment", C: "Edit Comment", D: "Page Layout" }, c: "C" },
        { s: "Excel", q: "Câu 296: Tham chiếu địa chỉ $A5:", o: { A: "Cột A cố định", B: "Hàng 5 cố định", C: "Cả 2 cố định", D: "Cả 2 thay đổi" }, c: "A" },
        { s: "Excel", q: "Câu 297: Thay đổi tỉ lệ giá trị trục biểu đồ:", o: { A: "Change Chart Type", B: "Select Data", C: "Format Axis", D: "Format Major Girdlines" }, c: "C" },
        { s: "Excel", q: "Câu 298: Thay đổi nguồn dữ liệu bảng trụ xoay:", o: { A: "Summarize Values By", B: "Refresh", C: "Show Value As", D: "Change Data Source" }, c: "D" },
        { s: "Excel", q: "Câu 299: Phân tích dữ liệu các cột trong PivotTable:", o: { A: "Values", B: "Row Labels", C: "Column Labels", D: "Choose fields" }, c: "A" },
        { s: "Excel", q: "Câu 300: Tự động định dạng kiểu cách vùng ô:", o: { A: "Chỉ định dạng mẫu", B: "Không tùy chỉnh", C: "Chỉ cho số", D: "Sử dụng định dạng mẫu có sẵn để định dạng" }, c: "D" },
        { s: "Excel", q: "Câu 301: Tạo định dạng số theo yêu cầu:", o: { A: "Time", B: "Custom", C: "Date", D: "Number" }, c: "B" },
        { s: "Excel", q: "Câu 302: Tạo định dạng tiền tệ có sẵn:", o: { A: "Currency", B: "Custom", C: "Time", D: "Accounting" }, c: "A" },
        { s: "Excel", q: "Câu 303: A1=3, A2=5, A3=SUM(A1:A2*{9,10}) kết quả Ctrl+Shift+Enter:", o: { A: "77", B: "136", C: "57", D: "95" }, c: "A" },
        { s: "Excel", q: "Câu 304: Hàm Vlookup có ý nghĩa gì:", o: { A: "Tra cứu hàng trên cùng", B: "Tra cứu cột thứ nhất của mảng và trả về giá trị", C: "Tổng số cột", D: "Tra cứu vec-tơ" }, c: "B" },
        { s: "Excel", q: "Câu 305: Công cụ phân tích dữ liệu bảng tính:", o: { A: "Charts", B: "Hyperlink", C: "Pivot Table", D: "Sparklines" }, c: "C" },
        { s: "Excel", q: "Câu 306: Phân tích, tổng hợp, đánh giá dữ liệu:", o: { A: "Sparkline", B: "Chart", C: "PivotTable", D: "Sort" }, c: "C" },
        { s: "Excel", q: "Câu 307: Chọn phát biểu sai về từ chối/chấp nhận dữ liệu:", o: { A: "Từ chối theo thời gian", B: "Chấp nhận theo vùng ô", C: "Bật chấp nhận thì dữ liệu cũ không lưu", D: "Từ chối theo tài khoản" }, c: "C" },
        { s: "Excel", q: "Câu 308: Tạo liên kết đến www.google.com:", o: { A: "Create New Document", B: "Place in This Document", C: "Text to display", D: "Existing File or WebPage" }, c: "D" },
        { s: "Excel", q: "Câu 309: Xóa liên kết được chọn:", o: { A: "Define Name", B: "Format Cells", C: "Edit HyperLink", D: "Remove Hyperlink" }, c: "D" },
        { s: "Excel", q: "Câu 310: Cập nhật liên kết đến Sheet 3:", o: { A: "E-mail Address", B: "Remove Link", C: "Place in This Document", D: "Create New Document" }, c: "C" },
        { s: "Excel", q: "Câu 311: Tạo thứ tự sắp xếp theo yêu cầu (tiếp theo):", o: { A: "General", B: "Edit Custom List", C: "Custom list", D: "Add level" }, c: "B" },
        { s: "Excel", q: "Câu 312: Hiển thị trang tính khác ra màn hình để so sánh:", o: { A: "Reset Window Position", B: "Switch Window", C: "New Window", D: "View Side by Side" }, c: "D" },
        { s: "Excel", q: "Câu 313: Chèn thêm trường vào đầu trang tính:", o: { A: "WordArt", B: "Text box", C: "Header", D: "Footer" }, c: "C" },
        { s: "Excel", q: "Câu 314: Thay đổi tỉ lệ đường kẻ trục hoành biểu đồ cột:", o: { A: "Vertical Axes", B: "Horizontal Girdlines", C: "Vertical Girdlines", D: "Horizontal Axes" }, c: "B" },
        { s: "Excel", q: "Câu 315: Sửa siêu liên kết được chọn:", o: { A: "Format Cells", B: "Remove hyperLink", C: "Edit HyperLink", D: "Define Name" }, c: "C" },
        { s: "Excel", q: "Câu 316: Sửa tiêu đề kiểm tra dữ liệu từ chữ sang số:", o: { A: "Data Validation/Settings/Validation criteria/Data", B: "Allow", C: "Minimum", D: "Maximum" }, c: "B" },
        { s: "Excel", q: "Câu 317: Sao chép giá trị của ô:", o: { A: "Value", B: "Comments", C: "Formats", D: "Formulas" }, c: "A" },
        { s: "Excel", q: "Câu 318: Ý nghĩa hàm DCOUNTA():", o: { A: "Đếm ô không trống trong CSDL", B: "Giá trị tối đa", C: "Đếm ô số", D: "Trích bản ghi" }, c: "A" },
        { s: "Excel", q: "Câu 319: Hoán đổi giá trị cột và dòng trong biểu đồ:", o: { A: "Series values", B: "Add", C: "Switch Row/Column", D: "column" }, c: "C" },
        { s: "Excel", q: "Câu 320: Sau khi thay đổi dữ liệu nguồn, kết quả bảng trụ:", o: { A: "Tự động cập nhật", B: "Bị xóa", C: "Nhập kết quả", D: "Không tự cập nhật" }, c: "D" },
        { s: "Excel", q: "Câu 321: Sử dụng mẫu (template) có sẵn của Microsoft:", o: { A: "File/Print", B: "File/Save", C: "File/Options", D: "File/New" }, c: "D" },
        { s: "Excel", q: "Câu 322: Sao chép biểu thức của ô:", o: { A: "Formats", B: "Formulas", C: "Comments", D: "Values" }, c: "B" },
        { s: "Excel", q: "Câu 323: Hàm tính tích số:", o: { A: "SUM()", B: "PRODUCT()", C: "COUNTA()", D: "SUMIF()" }, c: "B" },
        { s: "Excel", q: "Câu 324: Ý nghĩa hàm NOMINAL():", o: { A: "Tổng giá trị", B: "Lãi suất thực tế", C: "Trả về lãi suất danh nghĩa hàng năm", D: "Mức chiết khấu" }, c: "C" },
        { s: "Excel", q: "Câu 325: A1=11, A2=12, kết quả =AND(VALUE(A1)>10, VALUE(A2)<5)", o: { A: "FALSE", B: "#N/A", C: "#VALUE", D: "TRUE" }, c: "A" },
        { s: "Excel", q: "Câu 326: Chèn biểu đồ kết hợp cột và đường:", o: { A: "Bar", B: "Combo", C: "Column", D: "Line" }, c: "B" },
        { s: "Excel", q: "Câu 327: SUBTOTAL(9, ...), tham số 9 có ý nghĩa:", o: { A: "AVERAGE()", B: "SUM()", C: "COUNT()", D: "MAX()" }, c: "B" },
        { s: "Excel", q: "Câu 328: Chọn phát biểu sai về Validation:", o: { A: "Sửa thông báo lỗi", B: "Stop không cho phép nhận giá trị", C: "Information cho phép nhận giá trị", D: "Warning không cho phép nhận giá trị dù ngoài vùng" }, c: "D" },
        { s: "Excel", q: "Câu 329: Kết quả hàm ODD(225):", o: { A: "226", B: "15", C: "16", D: "225" }, c: "D" },
        { s: "Excel", q: "Câu 330: Tính giá trị trung bình cột trong PivotTable:", o: { A: "Sum", B: "Average", C: "Min", D: "Max" }, c: "B" },
        { s: "Excel", q: "Câu 331: Kết quả hàm SUMSQ(5,9):", o: { A: "105", B: "104", C: "107", D: "106" }, c: "B" },
        { s: "Excel", q: "Câu 332: A1=12:53:13, A2=IF(HOUR(A1>12), \"Đúng\", \"Sai\") cho kết quả:", o: { A: "Đúng", B: "False", C: "Sai", D: "True" }, c: "A" },
        { s: "Excel", q: "Câu 333: Thay đổi kiểu biểu đồ sang hình tròn:", o: { A: "Line", B: "Bar", C: "Pie", D: "Column" }, c: "C" },
        { s: "Excel", q: "Câu 334: Tạo định dạng có điều kiện theo nội dung ô:", o: { A: "New Rules", B: "New Cell Styles", C: "Cell Styles", D: "Conditional Formatting/Chọn mẫu" }, c: "A" },
        { s: "Excel", q: "Câu 335: Đặt tên cho vùng ô:", o: { A: "Use in Formula", B: "Define Name", C: "Create from Selection", D: "Apply Name" }, c: "B" },
        { s: "Excel", q: "Câu 336: Kết quả hàm SQRT(-225):", o: { A: "#NAME", B: "15", C: "-15", D: "#NUM" }, c: "D" },
        { s: "Excel", q: "Câu 337: A2=10*VALUE(\"Excel 2010\") cho kết quả:", o: { A: "#NAME", B: "2", C: "#VALUE", D: "5" }, c: "C" },

        // ================= PHẦN PROJECT (338 - 408) =================
        { s: "Project", q: "Câu 338: Chức năng Zoom out trong MS Project 2010:", o: { A: "Phóng to", B: "Hiển thị cửa sổ", C: "Thu nhỏ nội dung cửa sổ", D: "Tất cả sai" }, c: "C" },
        { s: "Project", q: "Câu 339: Dự án trong MS Project có thể xuất thành:", o: { A: "*.MPP", B: "Tất cả đều đúng", C: "*.PDF", D: "*.XPS" }, c: "B" },
        { s: "Project", q: "Câu 340: Con người và máy móc thuộc loại nguồn lực nào:", o: { A: "Work", B: "Cost", C: "Material", D: "Khác" }, c: "A" },
        { s: "Project", q: "Câu 341: Cơ chế tính phí 'prorated' tính vào lúc:", o: { A: "Dùng đến đâu tính đến đó, rải đều trong quá trình", B: "Bắt đầu", C: "Kết thúc", D: "Không có" }, c: "A" },
        { s: "Project", q: "Câu 342: Cách tính chi phí nguồn lực:", o: { A: "Work, Material, Cost", B: "Begin, Finish, Prorated", C: "Start, End, Prorated", D: "Standard, Night Shift, 24h" }, c: "A" },
        { s: "Project", q: "Câu 343: Thiết lập cột Max Units của một nguồn lực:", o: { A: "Advanced", B: "Display", C: "General", D: "Schedule/Show assignment units" }, c: "D" },
        { s: "Project", q: "Câu 344: Đường găng là chuỗi công việc ... để hoàn thành dự án:", o: { A: "Ngắn nhất", B: "Dài nhất", C: "Tối thiểu", D: "Khó nhất" }, c: "B" },
        { s: "Project", q: "Câu 345: Nguyên tắc cơ bản lựa chọn phương án triển khai dự án:", o: { A: "Tất cả phương án trên đều đúng", B: "Gần nguyên liệu", C: "Đảm bảo an ninh", D: "Chống ô nhiễm" }, c: "A" },
        { s: "Project", q: "Câu 346: Nhận định sai đối với sơ đồ PERT:", o: { A: "Tất cả đều sai", B: "Biểu diễn bằng cung mũi tên", C: "Một sự kiện đầu và cuối", D: "Đánh số từ trái sang phải" }, c: "A" },
        { s: "Project", q: "Câu 347: Quy trình Lập kế hoạch dự án:", o: { A: "1->9->4->2->3->5->7->6->8", B: "1->9->4->2->5->3->6->7->8", C: "1->2->3->4->5->6->7->8->9", D: "1->9->4->2->5->3->7->6->8" }, c: "B" },
        { s: "Project", q: "Câu 348: Thiết lập lịch làm việc cho dự án trong Microsoft Project:", o: { A: "Calculate project", B: "Custom fields", C: "Status date", D: "Change working time" }, c: "D" },
        { s: "Project", q: "Câu 349: Khi mở phần mềm quản lý dự án, màn hình mặc định hiển thị:", o: { A: "Task form", B: "Gantt chart", C: "Calendar", D: "Resource sheet" }, c: "B" },
        { s: "Project", q: "Câu 350: Để đẩy nhanh tiến độ dự án, tập trung đẩy nhanh:", o: { A: "Những công việc trên đường găng", B: "Tất cả công việc", C: "Không trường hợp nào", D: "Công việc không găng" }, c: "A" },
        { s: "Project", q: "Câu 351: Đơn vị tiền tệ 'đ':", o: { A: "Display/Symbol", B: "Schedule/Currency", C: "Advanced/Currency", D: "Advanced/Symbol" }, c: "C" },
        { s: "Project", q: "Câu 352: Earned Value là báo cáo:", o: { A: "Độ lệch chi phí", B: "Chi phí vượt dự trù", C: "Ngân quỹ dự trù", D: "Nguồn lực vượt chi phí" }, c: "A" },
        { s: "Project", q: "Câu 353: Thời gian dự trữ toàn phần của một công việc:", o: { A: "Chậm trễ không ảnh hưởng ngày hoàn thành toàn bộ dự án", B: "Không ảnh hưởng ngày bắt đầu sớm", C: "Không ảnh hưởng ngày bắt đầu kế tiếp", D: "Không ảnh hưởng ngày kết thúc kế tiếp" }, c: "A" },
        { s: "Project", q: "Câu 354: Dự án kinh doanh tối ưu nếu:", o: { A: "Tất cả phương án trên đều đúng", B: "Hiệu quả", C: "Thời gian", D: "Nguồn lực" }, c: "A" },
        { s: "Project", q: "Câu 355: Nguyên vật liệu thuộc loại nguồn lực nào:", o: { A: "Tất cả đều sai", B: "Material", C: "Work", D: "Cost" }, c: "B" },
        { s: "Project", q: "Câu 356: Chi phí thuộc loại nguồn lực nào:", o: { A: "Material", B: "Cost", C: "Tất cả đều sai", D: "Work" }, c: "B" },
        { s: "Project", q: "Câu 357: Overtime Rate là gì:", o: { A: "Mức giá làm trong giờ", B: "Chi phí cố định", C: "Mức giá cho những công việc ngoài giờ", D: "Cách tính phí" }, c: "C" },
        { s: "Project", q: "Câu 358: Khái niệm 'Task' trong Microsoft Project:", o: { A: "Khoảng thời gian", B: "Quản lý nguồn lực", C: "Hiển thị chi phí", D: "Đối tượng để quản lý công việc, điểm mốc trong dự án" }, c: "D" },
        { s: "Project", q: "Câu 359: Resource Sheet trong MS Project:", o: { A: "Mức độ sử dụng theo thời gian", B: "Dạng lịch", C: "Mức độ sử dụng nguồn lực", D: "Bảng khai báo các nguồn lực cho dự án bao gồm con người, vật tư, chi phí, máy móc" }, c: "D" },
        { s: "Project", q: "Câu 360: Phân bố nguồn lực cho công việc thông qua cửa sổ:", o: { A: "Task Usage", B: "Resource Graph", C: "Resource Sheet", D: "Team Planner" }, c: "A" },
        { s: "Project", q: "Câu 361: Biểu đồ Gantt cho biết:", o: { A: "Thời gian thực hiện", B: "Thời gian thực hiện, ngày bắt đầu, kết thúc và mối quan hệ tương đối", C: "Ngày bắt đầu, kết thúc", D: "Mối quan hệ" }, c: "B" },
        { s: "Project", q: "Câu 362: Nồi, chảo, bếp trong dự án làm bánh thuộc loại nguồn lực:", o: { A: "Cost", B: "Material", C: "Cả 3 đáp án đều đúng", D: "Work" }, c: "B" },
        { s: "Project", q: "Câu 363: Lập lịch công việc định kỳ:", o: { A: "Task/Recurring Task", B: "Project/Recurring Task", C: "Format/Recurring Task", D: "View/Recurring Task" }, c: "A" },
        { s: "Project", q: "Câu 364: Đánh dấu yêu cầu % Complete từ 50% trở lên:", o: { A: "does not equals 50%", B: "is less than 50%", C: "is greater than or equals to 50%", D: "is greater than 50%" }, c: "C" },
        { s: "Project", q: "Câu 365: Calendar trong MS Project:", o: { A: "Màn hình hiển thị các công việc dưới dạng lịch làm việc", B: "Bảng khai báo nguồn lực", C: "Mức độ sử dụng", D: "Thời gian" }, c: "A" },
        { s: "Project", q: "Câu 366: Task Sheet là gì:", o: { A: "Màn hình nhập liệu dạng bảng, tương tự Gantt Chart không có phần biểu đồ", B: "Master-detail theo nguồn lực", C: "Master-detail theo công việc", D: "Mức độ sử dụng" }, c: "A" },
        { s: "Project", q: "Câu 367: Công thức tính Total Cost:", o: { A: "(Work*Standard Rate) + (Overtime Work*Overtime Rate) + Per Use Cost + Fixed Cost", B: "Total + Baseline", C: "Actual Word...", D: "Actual + Remaining" }, c: "A" },
        { s: "Project", q: "Câu 368: Cột Material Label dùng để:", o: { A: "Nhập giá ngoài giờ", B: "Nhập cách tính phí", C: "Nhập giá trong giờ", D: "Nhập đơn vị tính" }, c: "D" },
        { s: "Project", q: "Câu 369: Lịch tính từ đêm thứ 2 đến sáng thứ 7 (23h đến 8h):", o: { A: "Night Shift", B: "Standard", C: "24 Hours", D: "Day Shift" }, c: "A" },
        { s: "Project", q: "Câu 370: Các loại lịch mặc định trong Microsoft Project:", o: { A: "Standard, 24 Hours, Day Shift", B: "Standard, Night Shift, 24 Hours", C: "Standard, Night Shift, Calendar", D: "Night Shift, 24 Hours, Calendar" }, c: "B" },
        { s: "Project", q: "Câu 371: Mục đích của quản lý thời gian:", o: { A: "Đúng hạn và đảm bảo chất lượng", B: "Đúng hạn tiến độ cơ sở đảm bảo chất lượng", C: "Đúng hạn tiến độ", D: "Đúng hạn và trong phạm vi ngân sách" }, c: "D" },
        { s: "Project", q: "Câu 372: Chỉ tiêu B/C đánh giá dự án độc lập, được chấp nhận khi:", o: { A: "B/C > 1", B: "B/C = 1", C: "B/C < 1", D: "B/C < 0" }, c: "A" },
        { s: "Project", q: "Câu 373: Đặt lịch làm việc cho nguồn lực chọn cột:", o: { A: "Max. Units", B: "Accrue At", C: "Type", D: "Base Calendar" }, c: "D" },
        { s: "Project", q: "Câu 374: Quản lý, kiểm tra mục tiêu và phạm vi công việc khi:", o: { A: "Khi dự án thực hiện", B: "Khi có rủi ro", C: "Khi kết thúc", D: "Khi bắt đầu" }, c: "A" },
        { s: "Project", q: "Câu 375: Nhập chi phí tài nguyên kiểu Cost chọn cửa sổ:", o: { A: "Resource Graph", B: "Resource Sheet", C: "Assign Resources", D: "Team Planner" }, c: "B" },
        { s: "Project", q: "Câu 376: Kế hoạch chi phí cực tiểu điều chỉnh chi phí:", o: { A: "Đẩy nhanh và rút ngắn công việc không găng", B: "Bình thường và rút ngắn công việc không găng", C: "Đẩy nhanh và rút ngắn công việc găng", D: "Bình thường và rút ngắn công việc găng" }, c: "D" },
        { s: "Project", q: "Câu 377: In báo cáo giám sát Earned Value:", o: { A: "Overview/Earned Value", B: "Assignments", C: "Cost/Earned Value", D: "Custom" }, c: "C" },
        { s: "Project", q: "Câu 378: Phần mềm nào không phải quản lý dự án:", o: { A: "Ants Project Management", B: "Smartsheet", C: "Microsoft SQL Server", D: "Microsoft Project" }, c: "C" },
        { s: "Project", q: "Câu 379: Lộ trình đúng của dự án:", o: { A: "Khởi tạo – Lập kế hoạch – Triển khai – Kết thúc", B: "Khởi tạo – Lập kế hoạch – Giám sát – Kết thúc", C: "Khởi tạo – Triển khai – Kiểm tra – Kết thúc", D: "Khởi tạo – Triển khai – Giám sát – Kết thúc" }, c: "B" },
        { s: "Project", q: "Câu 380: Phần mở rộng file MS Project:", o: { A: ".bat", B: ".bak", C: ".mpc", D: ".mpp" }, c: "D" },
        { s: "Project", q: "Câu 381: Resource Usage trong MS Project là:", o: { A: "Quan sát trực quan", B: "Mức độ sử dụng nguồn lực theo thời gian", C: "Dạng lịch", D: "Mức độ sử dụng công việc" }, c: "B" },
        { s: "Project", q: "Câu 382: WBS được viết tắt bởi:", o: { A: "Work Break Structure", B: "Work Break down Structure", C: "Work Break State", D: "Work Break down System" }, c: "B" },
        { s: "Project", q: "Câu 383: Đẩy nhanh tiến độ công việc chú trọng:", o: { A: "Công việc không mang tính quyết định", B: "Nhiều công việc nhất có thể", C: "Công việc trên đường găng", D: "Không cần" }, c: "C" },
        { s: "Project", q: "Câu 384: ACWP viết tắt của:", o: { A: "Actual Cost of Work Schedule", B: "Actual Cost of Work Performed", C: "Actual Cost of Work Variance", D: "Actual Cost of Work Baseline" }, c: "B" },
        { s: "Project", q: "Câu 385: Lịch từ thứ 2 đến thứ 6, từ 8h đến 17h:", o: { A: "Day Shift", B: "Standard", C: "24 hours", D: "Night Shift" }, c: "B" },
        { s: "Project", q: "Câu 386: Thời gian dự trữ tự do của một công việc:", o: { A: "Không ảnh hưởng ngày kết thúc công việc kế tiếp", B: "Không ảnh hưởng ngày bắt đầu sớm kế tiếp", C: "Không ảnh hưởng ngày bắt đầu sớm", D: "Không ảnh hưởng tiến độ toàn dự án" }, c: "B" },
        { s: "Project", q: "Câu 387: Thiết lập Status Date trong Project:", o: { A: "1-2-3-4-5-6-7-8-9", B: "1-2-5-3-6-4-7-8-9", C: "1-2-5-3-4-6-7-8-9", D: "1-2-5-4-3-6-7-8-9" }, c: "C" },
        { s: "Project", q: "Câu 388: Thiết lập VNĐ cho chi phí tài nguyên:", o: { A: "Schedule", B: "Advance", C: "General", D: "Display" }, c: "D" },
        { s: "Project", q: "Câu 389: Đường găng là đường có độ dài:", o: { A: "Bằng tổng thời gian", B: "Dài nhất đi từ sự kiện đầu đến cuối", C: "Ngắn nhất", D: "Trung bình" }, c: "B" },
        { s: "Project", q: "Câu 390: Độ dài đường găng cho biết:", o: { A: "Thời gian công việc A", B: "Thời gian đường găng", C: "Thời gian hoàn thành toàn bộ dự án", D: "Thời gian công việc không găng" }, c: "C" },
        { s: "Project", q: "Câu 391: Sai lầm về thời gian hoàn thành bằng cách tăng lao động:", o: { A: "Tăng lao động có thể không hiệu quả", B: "Tiến độ không phù hợp trình tự", C: "Không đủ không gian", D: "Tất cả các phương án trên" }, c: "D" },
        { s: "Project", q: "Câu 392: Nhập đơn vị tính nguồn lực (Kg, cái):", o: { A: "Material Label", B: "Type", C: "Units", D: "Resource Name" }, c: "A" },
        { s: "Project", q: "Câu 393: Chi phí cố định chọn Prorated có nghĩa là:", o: { A: "Áp dụng khi bắt đầu", B: "Khi kết thúc", C: "Phân bổ theo tỷ lệ % thực hiện của dự án", D: "Ngay lập tức" }, c: "C" },
        { s: "Project", q: "Câu 394: Standard Rate là gì:", o: { A: "Chi phí mỗi lần sử dụng", B: "Mức giá làm trong giờ", C: "Mức giá ngoài giờ", D: "Lựa chọn tính phí" }, c: "B" },
        { s: "Project", q: "Câu 395: Đường găng thể hiện thời gian ... để hoàn thành dự án:", o: { A: "Tối thiểu", B: "Ngắn nhất", C: "Dài nhất", D: "Tối đa" }, c: "A" },
        { s: "Project", q: "Câu 396: Thiết lập mức độ (Rất cao, Cao, Trung bình):", o: { A: "Task/Custom Fields/Lookup", B: "Project/Custom Fields/Lookup/Value", C: "Project/Custom Fields/Formula", D: "Project/Custom Fields/Lookup/Description" }, c: "B" },
        { s: "Project", q: "Câu 397: Đẩy nhanh tiến độ thực hiện dự án tập trung vào:", o: { A: "Nhiều công việc nhất có thể", B: "Công việc trên đường găng", C: "Công việc không găng", D: "Không trường hợp nào" }, c: "B" },
        { s: "Project", q: "Câu 398: Quản lý kiểm tra mục tiêu và phạm vi khi:", o: { A: "Bắt đầu", B: "Thực hiện", C: "Kết thúc", D: "Rủi ro phát sinh" }, c: "B" },
        { s: "Project", q: "Câu 399: Con người và máy móc thuộc loại nguồn lực:", o: { A: "Material", B: "Khác", C: "Cost", D: "Work" }, c: "D" },
        { s: "Project", q: "Câu 400: Hiển thị % hoàn thành và chi phí trên Gantt Chart:", o: { A: "Format/Format/Bar", B: "View/Format/Bar", C: "Format/Bar", D: "View/Bar" }, c: "C" },
        { s: "Project", q: "Câu 401: In báo cáo chi phí theo tiến độ giải ngân chọn:", o: { A: "Overbudget Tasks", B: "Cash Flow", C: "Budget", D: "Earned Value" }, c: "B" },
        { s: "Project", q: "Câu 402: Thiết lập cột Max Units:", o: { A: "General", B: "Display", C: "Advanced/Show assignment units", D: "Schedule" }, c: "C" },
        { s: "Project", q: "Câu 403: Quy trình Giám sát và Điều chỉnh dự án:", o: { A: "3->4->5->1->2->6->7->8", B: "1->2->3->4->5->6->7->8", C: "3->4->5->6->1->2->7->8", D: "2->3->4->5->1->6->7->8" }, c: "D" },
        { s: "Project", q: "Câu 404: WBS dùng để làm gì:", o: { A: "Xác định công việc, thời gian phân bổ nhân công, chi phí", B: "Xác định công việc cho từng hạng mục của dự án", C: "Nguồn tài trợ", D: "Nguyên liệu" }, c: "B" },
        { s: "Project", q: "Câu 405: Biểu đồ GANTT có nhiều tác dụng, trừ trường hợp:", o: { A: "Phản ánh chính xác mối quan hệ giữa các công việc phức tạp", B: "Phản ánh mối quan hệ", C: "Cho biết độ dài thời gian", D: "Tất cả" }, c: "A" },
        { s: "Project", q: "Câu 406: Thiết lập ngày Status Date vào 23/5:", o: { A: "Project Information", B: "Status Date", C: "View/Status Date", D: "Change Working Time" }, c: "B" },
        { s: "Project", q: "Câu 407: Thời gian dự trữ tự do của một công việc:", o: { A: "Không ảnh hưởng ngày hoàn thành toàn bộ", B: "Không ảnh hưởng ngày bắt đầu sớm của công việc kế tiếp", C: "Không ảnh hưởng ngày kết thúc", D: "Không ảnh hưởng ngày bắt đầu sớm" }, c: "B" },
        { s: "Project", q: "Câu 408: Công việc găng là công việc:", o: { A: "Thời gian dự trữ toàn phần bằng 0, tự do khác 0", B: "Thời gian dự trữ toàn phần và tự do bằng 0", C: "Có thời gian dự trữ toàn phần bằng 0", D: "Có thời gian dự trữ tự do bằng 0" }, c: "C" },
    ]
};